/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	v1 "github.com/trussle/terraform-operator/pkg/apis/aws/v1"
	scheme "github.com/trussle/terraform-operator/pkg/client/clientset/versioned/scheme"
	meta_v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// AwsApiGatewayBasePathMappingsGetter has a method to return a AwsApiGatewayBasePathMappingInterface.
// A group's client should implement this interface.
type AwsApiGatewayBasePathMappingsGetter interface {
	AwsApiGatewayBasePathMappings(namespace string) AwsApiGatewayBasePathMappingInterface
}

// AwsApiGatewayBasePathMappingInterface has methods to work with AwsApiGatewayBasePathMapping resources.
type AwsApiGatewayBasePathMappingInterface interface {
	Create(*v1.AwsApiGatewayBasePathMapping) (*v1.AwsApiGatewayBasePathMapping, error)
	Update(*v1.AwsApiGatewayBasePathMapping) (*v1.AwsApiGatewayBasePathMapping, error)
	Delete(name string, options *meta_v1.DeleteOptions) error
	DeleteCollection(options *meta_v1.DeleteOptions, listOptions meta_v1.ListOptions) error
	Get(name string, options meta_v1.GetOptions) (*v1.AwsApiGatewayBasePathMapping, error)
	List(opts meta_v1.ListOptions) (*v1.AwsApiGatewayBasePathMappingList, error)
	Watch(opts meta_v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.AwsApiGatewayBasePathMapping, err error)
	AwsApiGatewayBasePathMappingExpansion
}

// awsApiGatewayBasePathMappings implements AwsApiGatewayBasePathMappingInterface
type awsApiGatewayBasePathMappings struct {
	client rest.Interface
	ns     string
}

// newAwsApiGatewayBasePathMappings returns a AwsApiGatewayBasePathMappings
func newAwsApiGatewayBasePathMappings(c *TrussleV1Client, namespace string) *awsApiGatewayBasePathMappings {
	return &awsApiGatewayBasePathMappings{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the awsApiGatewayBasePathMapping, and returns the corresponding awsApiGatewayBasePathMapping object, and an error if there is any.
func (c *awsApiGatewayBasePathMappings) Get(name string, options meta_v1.GetOptions) (result *v1.AwsApiGatewayBasePathMapping, err error) {
	result = &v1.AwsApiGatewayBasePathMapping{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("awsapigatewaybasepathmappings").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of AwsApiGatewayBasePathMappings that match those selectors.
func (c *awsApiGatewayBasePathMappings) List(opts meta_v1.ListOptions) (result *v1.AwsApiGatewayBasePathMappingList, err error) {
	result = &v1.AwsApiGatewayBasePathMappingList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("awsapigatewaybasepathmappings").
		VersionedParams(&opts, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested awsApiGatewayBasePathMappings.
func (c *awsApiGatewayBasePathMappings) Watch(opts meta_v1.ListOptions) (watch.Interface, error) {
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("awsapigatewaybasepathmappings").
		VersionedParams(&opts, scheme.ParameterCodec).
		Watch()
}

// Create takes the representation of a awsApiGatewayBasePathMapping and creates it.  Returns the server's representation of the awsApiGatewayBasePathMapping, and an error, if there is any.
func (c *awsApiGatewayBasePathMappings) Create(awsApiGatewayBasePathMapping *v1.AwsApiGatewayBasePathMapping) (result *v1.AwsApiGatewayBasePathMapping, err error) {
	result = &v1.AwsApiGatewayBasePathMapping{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("awsapigatewaybasepathmappings").
		Body(awsApiGatewayBasePathMapping).
		Do().
		Into(result)
	return
}

// Update takes the representation of a awsApiGatewayBasePathMapping and updates it. Returns the server's representation of the awsApiGatewayBasePathMapping, and an error, if there is any.
func (c *awsApiGatewayBasePathMappings) Update(awsApiGatewayBasePathMapping *v1.AwsApiGatewayBasePathMapping) (result *v1.AwsApiGatewayBasePathMapping, err error) {
	result = &v1.AwsApiGatewayBasePathMapping{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("awsapigatewaybasepathmappings").
		Name(awsApiGatewayBasePathMapping.Name).
		Body(awsApiGatewayBasePathMapping).
		Do().
		Into(result)
	return
}

// Delete takes name of the awsApiGatewayBasePathMapping and deletes it. Returns an error if one occurs.
func (c *awsApiGatewayBasePathMappings) Delete(name string, options *meta_v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("awsapigatewaybasepathmappings").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *awsApiGatewayBasePathMappings) DeleteCollection(options *meta_v1.DeleteOptions, listOptions meta_v1.ListOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("awsapigatewaybasepathmappings").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched awsApiGatewayBasePathMapping.
func (c *awsApiGatewayBasePathMappings) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.AwsApiGatewayBasePathMapping, err error) {
	result = &v1.AwsApiGatewayBasePathMapping{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("awsapigatewaybasepathmappings").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
