/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	v1 "github.com/trussle/terraform-operator/pkg/apis/aws/v1"
	scheme "github.com/trussle/terraform-operator/pkg/client/clientset/versioned/scheme"
	meta_v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// AwsAlbListenersGetter has a method to return a AwsAlbListenerInterface.
// A group's client should implement this interface.
type AwsAlbListenersGetter interface {
	AwsAlbListeners(namespace string) AwsAlbListenerInterface
}

// AwsAlbListenerInterface has methods to work with AwsAlbListener resources.
type AwsAlbListenerInterface interface {
	Create(*v1.AwsAlbListener) (*v1.AwsAlbListener, error)
	Update(*v1.AwsAlbListener) (*v1.AwsAlbListener, error)
	Delete(name string, options *meta_v1.DeleteOptions) error
	DeleteCollection(options *meta_v1.DeleteOptions, listOptions meta_v1.ListOptions) error
	Get(name string, options meta_v1.GetOptions) (*v1.AwsAlbListener, error)
	List(opts meta_v1.ListOptions) (*v1.AwsAlbListenerList, error)
	Watch(opts meta_v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.AwsAlbListener, err error)
	AwsAlbListenerExpansion
}

// awsAlbListeners implements AwsAlbListenerInterface
type awsAlbListeners struct {
	client rest.Interface
	ns     string
}

// newAwsAlbListeners returns a AwsAlbListeners
func newAwsAlbListeners(c *TrussleV1Client, namespace string) *awsAlbListeners {
	return &awsAlbListeners{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the awsAlbListener, and returns the corresponding awsAlbListener object, and an error if there is any.
func (c *awsAlbListeners) Get(name string, options meta_v1.GetOptions) (result *v1.AwsAlbListener, err error) {
	result = &v1.AwsAlbListener{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("awsalblisteners").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of AwsAlbListeners that match those selectors.
func (c *awsAlbListeners) List(opts meta_v1.ListOptions) (result *v1.AwsAlbListenerList, err error) {
	result = &v1.AwsAlbListenerList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("awsalblisteners").
		VersionedParams(&opts, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested awsAlbListeners.
func (c *awsAlbListeners) Watch(opts meta_v1.ListOptions) (watch.Interface, error) {
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("awsalblisteners").
		VersionedParams(&opts, scheme.ParameterCodec).
		Watch()
}

// Create takes the representation of a awsAlbListener and creates it.  Returns the server's representation of the awsAlbListener, and an error, if there is any.
func (c *awsAlbListeners) Create(awsAlbListener *v1.AwsAlbListener) (result *v1.AwsAlbListener, err error) {
	result = &v1.AwsAlbListener{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("awsalblisteners").
		Body(awsAlbListener).
		Do().
		Into(result)
	return
}

// Update takes the representation of a awsAlbListener and updates it. Returns the server's representation of the awsAlbListener, and an error, if there is any.
func (c *awsAlbListeners) Update(awsAlbListener *v1.AwsAlbListener) (result *v1.AwsAlbListener, err error) {
	result = &v1.AwsAlbListener{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("awsalblisteners").
		Name(awsAlbListener.Name).
		Body(awsAlbListener).
		Do().
		Into(result)
	return
}

// Delete takes name of the awsAlbListener and deletes it. Returns an error if one occurs.
func (c *awsAlbListeners) Delete(name string, options *meta_v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("awsalblisteners").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *awsAlbListeners) DeleteCollection(options *meta_v1.DeleteOptions, listOptions meta_v1.ListOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("awsalblisteners").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched awsAlbListener.
func (c *awsAlbListeners) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.AwsAlbListener, err error) {
	result = &v1.AwsAlbListener{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("awsalblisteners").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
