/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	v1 "github.com/trussle/terraform-operator/pkg/apis/aws/v1"
	scheme "github.com/trussle/terraform-operator/pkg/client/clientset/versioned/scheme"
	meta_v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// AwsCloudfrontOriginAccessIdentitiesGetter has a method to return a AwsCloudfrontOriginAccessIdentityInterface.
// A group's client should implement this interface.
type AwsCloudfrontOriginAccessIdentitiesGetter interface {
	AwsCloudfrontOriginAccessIdentities(namespace string) AwsCloudfrontOriginAccessIdentityInterface
}

// AwsCloudfrontOriginAccessIdentityInterface has methods to work with AwsCloudfrontOriginAccessIdentity resources.
type AwsCloudfrontOriginAccessIdentityInterface interface {
	Create(*v1.AwsCloudfrontOriginAccessIdentity) (*v1.AwsCloudfrontOriginAccessIdentity, error)
	Update(*v1.AwsCloudfrontOriginAccessIdentity) (*v1.AwsCloudfrontOriginAccessIdentity, error)
	Delete(name string, options *meta_v1.DeleteOptions) error
	DeleteCollection(options *meta_v1.DeleteOptions, listOptions meta_v1.ListOptions) error
	Get(name string, options meta_v1.GetOptions) (*v1.AwsCloudfrontOriginAccessIdentity, error)
	List(opts meta_v1.ListOptions) (*v1.AwsCloudfrontOriginAccessIdentityList, error)
	Watch(opts meta_v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.AwsCloudfrontOriginAccessIdentity, err error)
	AwsCloudfrontOriginAccessIdentityExpansion
}

// awsCloudfrontOriginAccessIdentities implements AwsCloudfrontOriginAccessIdentityInterface
type awsCloudfrontOriginAccessIdentities struct {
	client rest.Interface
	ns     string
}

// newAwsCloudfrontOriginAccessIdentities returns a AwsCloudfrontOriginAccessIdentities
func newAwsCloudfrontOriginAccessIdentities(c *TrussleV1Client, namespace string) *awsCloudfrontOriginAccessIdentities {
	return &awsCloudfrontOriginAccessIdentities{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the awsCloudfrontOriginAccessIdentity, and returns the corresponding awsCloudfrontOriginAccessIdentity object, and an error if there is any.
func (c *awsCloudfrontOriginAccessIdentities) Get(name string, options meta_v1.GetOptions) (result *v1.AwsCloudfrontOriginAccessIdentity, err error) {
	result = &v1.AwsCloudfrontOriginAccessIdentity{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("awscloudfrontoriginaccessidentities").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of AwsCloudfrontOriginAccessIdentities that match those selectors.
func (c *awsCloudfrontOriginAccessIdentities) List(opts meta_v1.ListOptions) (result *v1.AwsCloudfrontOriginAccessIdentityList, err error) {
	result = &v1.AwsCloudfrontOriginAccessIdentityList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("awscloudfrontoriginaccessidentities").
		VersionedParams(&opts, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested awsCloudfrontOriginAccessIdentities.
func (c *awsCloudfrontOriginAccessIdentities) Watch(opts meta_v1.ListOptions) (watch.Interface, error) {
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("awscloudfrontoriginaccessidentities").
		VersionedParams(&opts, scheme.ParameterCodec).
		Watch()
}

// Create takes the representation of a awsCloudfrontOriginAccessIdentity and creates it.  Returns the server's representation of the awsCloudfrontOriginAccessIdentity, and an error, if there is any.
func (c *awsCloudfrontOriginAccessIdentities) Create(awsCloudfrontOriginAccessIdentity *v1.AwsCloudfrontOriginAccessIdentity) (result *v1.AwsCloudfrontOriginAccessIdentity, err error) {
	result = &v1.AwsCloudfrontOriginAccessIdentity{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("awscloudfrontoriginaccessidentities").
		Body(awsCloudfrontOriginAccessIdentity).
		Do().
		Into(result)
	return
}

// Update takes the representation of a awsCloudfrontOriginAccessIdentity and updates it. Returns the server's representation of the awsCloudfrontOriginAccessIdentity, and an error, if there is any.
func (c *awsCloudfrontOriginAccessIdentities) Update(awsCloudfrontOriginAccessIdentity *v1.AwsCloudfrontOriginAccessIdentity) (result *v1.AwsCloudfrontOriginAccessIdentity, err error) {
	result = &v1.AwsCloudfrontOriginAccessIdentity{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("awscloudfrontoriginaccessidentities").
		Name(awsCloudfrontOriginAccessIdentity.Name).
		Body(awsCloudfrontOriginAccessIdentity).
		Do().
		Into(result)
	return
}

// Delete takes name of the awsCloudfrontOriginAccessIdentity and deletes it. Returns an error if one occurs.
func (c *awsCloudfrontOriginAccessIdentities) Delete(name string, options *meta_v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("awscloudfrontoriginaccessidentities").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *awsCloudfrontOriginAccessIdentities) DeleteCollection(options *meta_v1.DeleteOptions, listOptions meta_v1.ListOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("awscloudfrontoriginaccessidentities").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched awsCloudfrontOriginAccessIdentity.
func (c *awsCloudfrontOriginAccessIdentities) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.AwsCloudfrontOriginAccessIdentity, err error) {
	result = &v1.AwsCloudfrontOriginAccessIdentity{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("awscloudfrontoriginaccessidentities").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
