/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	v1 "github.com/trussle/terraform-operator/pkg/apis/aws/v1"
	scheme "github.com/trussle/terraform-operator/pkg/client/clientset/versioned/scheme"
	meta_v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// AwsCloudwatchLogMetricFiltersGetter has a method to return a AwsCloudwatchLogMetricFilterInterface.
// A group's client should implement this interface.
type AwsCloudwatchLogMetricFiltersGetter interface {
	AwsCloudwatchLogMetricFilters(namespace string) AwsCloudwatchLogMetricFilterInterface
}

// AwsCloudwatchLogMetricFilterInterface has methods to work with AwsCloudwatchLogMetricFilter resources.
type AwsCloudwatchLogMetricFilterInterface interface {
	Create(*v1.AwsCloudwatchLogMetricFilter) (*v1.AwsCloudwatchLogMetricFilter, error)
	Update(*v1.AwsCloudwatchLogMetricFilter) (*v1.AwsCloudwatchLogMetricFilter, error)
	Delete(name string, options *meta_v1.DeleteOptions) error
	DeleteCollection(options *meta_v1.DeleteOptions, listOptions meta_v1.ListOptions) error
	Get(name string, options meta_v1.GetOptions) (*v1.AwsCloudwatchLogMetricFilter, error)
	List(opts meta_v1.ListOptions) (*v1.AwsCloudwatchLogMetricFilterList, error)
	Watch(opts meta_v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.AwsCloudwatchLogMetricFilter, err error)
	AwsCloudwatchLogMetricFilterExpansion
}

// awsCloudwatchLogMetricFilters implements AwsCloudwatchLogMetricFilterInterface
type awsCloudwatchLogMetricFilters struct {
	client rest.Interface
	ns     string
}

// newAwsCloudwatchLogMetricFilters returns a AwsCloudwatchLogMetricFilters
func newAwsCloudwatchLogMetricFilters(c *TrussleV1Client, namespace string) *awsCloudwatchLogMetricFilters {
	return &awsCloudwatchLogMetricFilters{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the awsCloudwatchLogMetricFilter, and returns the corresponding awsCloudwatchLogMetricFilter object, and an error if there is any.
func (c *awsCloudwatchLogMetricFilters) Get(name string, options meta_v1.GetOptions) (result *v1.AwsCloudwatchLogMetricFilter, err error) {
	result = &v1.AwsCloudwatchLogMetricFilter{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("awscloudwatchlogmetricfilters").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of AwsCloudwatchLogMetricFilters that match those selectors.
func (c *awsCloudwatchLogMetricFilters) List(opts meta_v1.ListOptions) (result *v1.AwsCloudwatchLogMetricFilterList, err error) {
	result = &v1.AwsCloudwatchLogMetricFilterList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("awscloudwatchlogmetricfilters").
		VersionedParams(&opts, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested awsCloudwatchLogMetricFilters.
func (c *awsCloudwatchLogMetricFilters) Watch(opts meta_v1.ListOptions) (watch.Interface, error) {
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("awscloudwatchlogmetricfilters").
		VersionedParams(&opts, scheme.ParameterCodec).
		Watch()
}

// Create takes the representation of a awsCloudwatchLogMetricFilter and creates it.  Returns the server's representation of the awsCloudwatchLogMetricFilter, and an error, if there is any.
func (c *awsCloudwatchLogMetricFilters) Create(awsCloudwatchLogMetricFilter *v1.AwsCloudwatchLogMetricFilter) (result *v1.AwsCloudwatchLogMetricFilter, err error) {
	result = &v1.AwsCloudwatchLogMetricFilter{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("awscloudwatchlogmetricfilters").
		Body(awsCloudwatchLogMetricFilter).
		Do().
		Into(result)
	return
}

// Update takes the representation of a awsCloudwatchLogMetricFilter and updates it. Returns the server's representation of the awsCloudwatchLogMetricFilter, and an error, if there is any.
func (c *awsCloudwatchLogMetricFilters) Update(awsCloudwatchLogMetricFilter *v1.AwsCloudwatchLogMetricFilter) (result *v1.AwsCloudwatchLogMetricFilter, err error) {
	result = &v1.AwsCloudwatchLogMetricFilter{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("awscloudwatchlogmetricfilters").
		Name(awsCloudwatchLogMetricFilter.Name).
		Body(awsCloudwatchLogMetricFilter).
		Do().
		Into(result)
	return
}

// Delete takes name of the awsCloudwatchLogMetricFilter and deletes it. Returns an error if one occurs.
func (c *awsCloudwatchLogMetricFilters) Delete(name string, options *meta_v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("awscloudwatchlogmetricfilters").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *awsCloudwatchLogMetricFilters) DeleteCollection(options *meta_v1.DeleteOptions, listOptions meta_v1.ListOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("awscloudwatchlogmetricfilters").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched awsCloudwatchLogMetricFilter.
func (c *awsCloudwatchLogMetricFilters) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.AwsCloudwatchLogMetricFilter, err error) {
	result = &v1.AwsCloudwatchLogMetricFilter{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("awscloudwatchlogmetricfilters").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
