/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	v1 "github.com/trussle/terraform-operator/pkg/apis/aws/v1"
	scheme "github.com/trussle/terraform-operator/pkg/client/clientset/versioned/scheme"
	meta_v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// AwsDmsReplicationSubnetGroupsGetter has a method to return a AwsDmsReplicationSubnetGroupInterface.
// A group's client should implement this interface.
type AwsDmsReplicationSubnetGroupsGetter interface {
	AwsDmsReplicationSubnetGroups(namespace string) AwsDmsReplicationSubnetGroupInterface
}

// AwsDmsReplicationSubnetGroupInterface has methods to work with AwsDmsReplicationSubnetGroup resources.
type AwsDmsReplicationSubnetGroupInterface interface {
	Create(*v1.AwsDmsReplicationSubnetGroup) (*v1.AwsDmsReplicationSubnetGroup, error)
	Update(*v1.AwsDmsReplicationSubnetGroup) (*v1.AwsDmsReplicationSubnetGroup, error)
	Delete(name string, options *meta_v1.DeleteOptions) error
	DeleteCollection(options *meta_v1.DeleteOptions, listOptions meta_v1.ListOptions) error
	Get(name string, options meta_v1.GetOptions) (*v1.AwsDmsReplicationSubnetGroup, error)
	List(opts meta_v1.ListOptions) (*v1.AwsDmsReplicationSubnetGroupList, error)
	Watch(opts meta_v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.AwsDmsReplicationSubnetGroup, err error)
	AwsDmsReplicationSubnetGroupExpansion
}

// awsDmsReplicationSubnetGroups implements AwsDmsReplicationSubnetGroupInterface
type awsDmsReplicationSubnetGroups struct {
	client rest.Interface
	ns     string
}

// newAwsDmsReplicationSubnetGroups returns a AwsDmsReplicationSubnetGroups
func newAwsDmsReplicationSubnetGroups(c *TrussleV1Client, namespace string) *awsDmsReplicationSubnetGroups {
	return &awsDmsReplicationSubnetGroups{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the awsDmsReplicationSubnetGroup, and returns the corresponding awsDmsReplicationSubnetGroup object, and an error if there is any.
func (c *awsDmsReplicationSubnetGroups) Get(name string, options meta_v1.GetOptions) (result *v1.AwsDmsReplicationSubnetGroup, err error) {
	result = &v1.AwsDmsReplicationSubnetGroup{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("awsdmsreplicationsubnetgroups").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of AwsDmsReplicationSubnetGroups that match those selectors.
func (c *awsDmsReplicationSubnetGroups) List(opts meta_v1.ListOptions) (result *v1.AwsDmsReplicationSubnetGroupList, err error) {
	result = &v1.AwsDmsReplicationSubnetGroupList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("awsdmsreplicationsubnetgroups").
		VersionedParams(&opts, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested awsDmsReplicationSubnetGroups.
func (c *awsDmsReplicationSubnetGroups) Watch(opts meta_v1.ListOptions) (watch.Interface, error) {
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("awsdmsreplicationsubnetgroups").
		VersionedParams(&opts, scheme.ParameterCodec).
		Watch()
}

// Create takes the representation of a awsDmsReplicationSubnetGroup and creates it.  Returns the server's representation of the awsDmsReplicationSubnetGroup, and an error, if there is any.
func (c *awsDmsReplicationSubnetGroups) Create(awsDmsReplicationSubnetGroup *v1.AwsDmsReplicationSubnetGroup) (result *v1.AwsDmsReplicationSubnetGroup, err error) {
	result = &v1.AwsDmsReplicationSubnetGroup{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("awsdmsreplicationsubnetgroups").
		Body(awsDmsReplicationSubnetGroup).
		Do().
		Into(result)
	return
}

// Update takes the representation of a awsDmsReplicationSubnetGroup and updates it. Returns the server's representation of the awsDmsReplicationSubnetGroup, and an error, if there is any.
func (c *awsDmsReplicationSubnetGroups) Update(awsDmsReplicationSubnetGroup *v1.AwsDmsReplicationSubnetGroup) (result *v1.AwsDmsReplicationSubnetGroup, err error) {
	result = &v1.AwsDmsReplicationSubnetGroup{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("awsdmsreplicationsubnetgroups").
		Name(awsDmsReplicationSubnetGroup.Name).
		Body(awsDmsReplicationSubnetGroup).
		Do().
		Into(result)
	return
}

// Delete takes name of the awsDmsReplicationSubnetGroup and deletes it. Returns an error if one occurs.
func (c *awsDmsReplicationSubnetGroups) Delete(name string, options *meta_v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("awsdmsreplicationsubnetgroups").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *awsDmsReplicationSubnetGroups) DeleteCollection(options *meta_v1.DeleteOptions, listOptions meta_v1.ListOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("awsdmsreplicationsubnetgroups").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched awsDmsReplicationSubnetGroup.
func (c *awsDmsReplicationSubnetGroups) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.AwsDmsReplicationSubnetGroup, err error) {
	result = &v1.AwsDmsReplicationSubnetGroup{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("awsdmsreplicationsubnetgroups").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
