/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	v1 "github.com/trussle/terraform-operator/pkg/apis/aws/v1"
	scheme "github.com/trussle/terraform-operator/pkg/client/clientset/versioned/scheme"
	meta_v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// AwsElasticBeanstalkApplicationVersionsGetter has a method to return a AwsElasticBeanstalkApplicationVersionInterface.
// A group's client should implement this interface.
type AwsElasticBeanstalkApplicationVersionsGetter interface {
	AwsElasticBeanstalkApplicationVersions(namespace string) AwsElasticBeanstalkApplicationVersionInterface
}

// AwsElasticBeanstalkApplicationVersionInterface has methods to work with AwsElasticBeanstalkApplicationVersion resources.
type AwsElasticBeanstalkApplicationVersionInterface interface {
	Create(*v1.AwsElasticBeanstalkApplicationVersion) (*v1.AwsElasticBeanstalkApplicationVersion, error)
	Update(*v1.AwsElasticBeanstalkApplicationVersion) (*v1.AwsElasticBeanstalkApplicationVersion, error)
	Delete(name string, options *meta_v1.DeleteOptions) error
	DeleteCollection(options *meta_v1.DeleteOptions, listOptions meta_v1.ListOptions) error
	Get(name string, options meta_v1.GetOptions) (*v1.AwsElasticBeanstalkApplicationVersion, error)
	List(opts meta_v1.ListOptions) (*v1.AwsElasticBeanstalkApplicationVersionList, error)
	Watch(opts meta_v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.AwsElasticBeanstalkApplicationVersion, err error)
	AwsElasticBeanstalkApplicationVersionExpansion
}

// awsElasticBeanstalkApplicationVersions implements AwsElasticBeanstalkApplicationVersionInterface
type awsElasticBeanstalkApplicationVersions struct {
	client rest.Interface
	ns     string
}

// newAwsElasticBeanstalkApplicationVersions returns a AwsElasticBeanstalkApplicationVersions
func newAwsElasticBeanstalkApplicationVersions(c *TrussleV1Client, namespace string) *awsElasticBeanstalkApplicationVersions {
	return &awsElasticBeanstalkApplicationVersions{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the awsElasticBeanstalkApplicationVersion, and returns the corresponding awsElasticBeanstalkApplicationVersion object, and an error if there is any.
func (c *awsElasticBeanstalkApplicationVersions) Get(name string, options meta_v1.GetOptions) (result *v1.AwsElasticBeanstalkApplicationVersion, err error) {
	result = &v1.AwsElasticBeanstalkApplicationVersion{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("awselasticbeanstalkapplicationversions").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of AwsElasticBeanstalkApplicationVersions that match those selectors.
func (c *awsElasticBeanstalkApplicationVersions) List(opts meta_v1.ListOptions) (result *v1.AwsElasticBeanstalkApplicationVersionList, err error) {
	result = &v1.AwsElasticBeanstalkApplicationVersionList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("awselasticbeanstalkapplicationversions").
		VersionedParams(&opts, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested awsElasticBeanstalkApplicationVersions.
func (c *awsElasticBeanstalkApplicationVersions) Watch(opts meta_v1.ListOptions) (watch.Interface, error) {
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("awselasticbeanstalkapplicationversions").
		VersionedParams(&opts, scheme.ParameterCodec).
		Watch()
}

// Create takes the representation of a awsElasticBeanstalkApplicationVersion and creates it.  Returns the server's representation of the awsElasticBeanstalkApplicationVersion, and an error, if there is any.
func (c *awsElasticBeanstalkApplicationVersions) Create(awsElasticBeanstalkApplicationVersion *v1.AwsElasticBeanstalkApplicationVersion) (result *v1.AwsElasticBeanstalkApplicationVersion, err error) {
	result = &v1.AwsElasticBeanstalkApplicationVersion{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("awselasticbeanstalkapplicationversions").
		Body(awsElasticBeanstalkApplicationVersion).
		Do().
		Into(result)
	return
}

// Update takes the representation of a awsElasticBeanstalkApplicationVersion and updates it. Returns the server's representation of the awsElasticBeanstalkApplicationVersion, and an error, if there is any.
func (c *awsElasticBeanstalkApplicationVersions) Update(awsElasticBeanstalkApplicationVersion *v1.AwsElasticBeanstalkApplicationVersion) (result *v1.AwsElasticBeanstalkApplicationVersion, err error) {
	result = &v1.AwsElasticBeanstalkApplicationVersion{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("awselasticbeanstalkapplicationversions").
		Name(awsElasticBeanstalkApplicationVersion.Name).
		Body(awsElasticBeanstalkApplicationVersion).
		Do().
		Into(result)
	return
}

// Delete takes name of the awsElasticBeanstalkApplicationVersion and deletes it. Returns an error if one occurs.
func (c *awsElasticBeanstalkApplicationVersions) Delete(name string, options *meta_v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("awselasticbeanstalkapplicationversions").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *awsElasticBeanstalkApplicationVersions) DeleteCollection(options *meta_v1.DeleteOptions, listOptions meta_v1.ListOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("awselasticbeanstalkapplicationversions").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched awsElasticBeanstalkApplicationVersion.
func (c *awsElasticBeanstalkApplicationVersions) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.AwsElasticBeanstalkApplicationVersion, err error) {
	result = &v1.AwsElasticBeanstalkApplicationVersion{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("awselasticbeanstalkapplicationversions").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
