/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	v1 "github.com/trussle/terraform-operator/pkg/apis/aws/v1"
	scheme "github.com/trussle/terraform-operator/pkg/client/clientset/versioned/scheme"
	meta_v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// AwsIamGroupPolicyAttachmentsGetter has a method to return a AwsIamGroupPolicyAttachmentInterface.
// A group's client should implement this interface.
type AwsIamGroupPolicyAttachmentsGetter interface {
	AwsIamGroupPolicyAttachments(namespace string) AwsIamGroupPolicyAttachmentInterface
}

// AwsIamGroupPolicyAttachmentInterface has methods to work with AwsIamGroupPolicyAttachment resources.
type AwsIamGroupPolicyAttachmentInterface interface {
	Create(*v1.AwsIamGroupPolicyAttachment) (*v1.AwsIamGroupPolicyAttachment, error)
	Update(*v1.AwsIamGroupPolicyAttachment) (*v1.AwsIamGroupPolicyAttachment, error)
	Delete(name string, options *meta_v1.DeleteOptions) error
	DeleteCollection(options *meta_v1.DeleteOptions, listOptions meta_v1.ListOptions) error
	Get(name string, options meta_v1.GetOptions) (*v1.AwsIamGroupPolicyAttachment, error)
	List(opts meta_v1.ListOptions) (*v1.AwsIamGroupPolicyAttachmentList, error)
	Watch(opts meta_v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.AwsIamGroupPolicyAttachment, err error)
	AwsIamGroupPolicyAttachmentExpansion
}

// awsIamGroupPolicyAttachments implements AwsIamGroupPolicyAttachmentInterface
type awsIamGroupPolicyAttachments struct {
	client rest.Interface
	ns     string
}

// newAwsIamGroupPolicyAttachments returns a AwsIamGroupPolicyAttachments
func newAwsIamGroupPolicyAttachments(c *TrussleV1Client, namespace string) *awsIamGroupPolicyAttachments {
	return &awsIamGroupPolicyAttachments{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the awsIamGroupPolicyAttachment, and returns the corresponding awsIamGroupPolicyAttachment object, and an error if there is any.
func (c *awsIamGroupPolicyAttachments) Get(name string, options meta_v1.GetOptions) (result *v1.AwsIamGroupPolicyAttachment, err error) {
	result = &v1.AwsIamGroupPolicyAttachment{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("awsiamgrouppolicyattachments").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of AwsIamGroupPolicyAttachments that match those selectors.
func (c *awsIamGroupPolicyAttachments) List(opts meta_v1.ListOptions) (result *v1.AwsIamGroupPolicyAttachmentList, err error) {
	result = &v1.AwsIamGroupPolicyAttachmentList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("awsiamgrouppolicyattachments").
		VersionedParams(&opts, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested awsIamGroupPolicyAttachments.
func (c *awsIamGroupPolicyAttachments) Watch(opts meta_v1.ListOptions) (watch.Interface, error) {
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("awsiamgrouppolicyattachments").
		VersionedParams(&opts, scheme.ParameterCodec).
		Watch()
}

// Create takes the representation of a awsIamGroupPolicyAttachment and creates it.  Returns the server's representation of the awsIamGroupPolicyAttachment, and an error, if there is any.
func (c *awsIamGroupPolicyAttachments) Create(awsIamGroupPolicyAttachment *v1.AwsIamGroupPolicyAttachment) (result *v1.AwsIamGroupPolicyAttachment, err error) {
	result = &v1.AwsIamGroupPolicyAttachment{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("awsiamgrouppolicyattachments").
		Body(awsIamGroupPolicyAttachment).
		Do().
		Into(result)
	return
}

// Update takes the representation of a awsIamGroupPolicyAttachment and updates it. Returns the server's representation of the awsIamGroupPolicyAttachment, and an error, if there is any.
func (c *awsIamGroupPolicyAttachments) Update(awsIamGroupPolicyAttachment *v1.AwsIamGroupPolicyAttachment) (result *v1.AwsIamGroupPolicyAttachment, err error) {
	result = &v1.AwsIamGroupPolicyAttachment{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("awsiamgrouppolicyattachments").
		Name(awsIamGroupPolicyAttachment.Name).
		Body(awsIamGroupPolicyAttachment).
		Do().
		Into(result)
	return
}

// Delete takes name of the awsIamGroupPolicyAttachment and deletes it. Returns an error if one occurs.
func (c *awsIamGroupPolicyAttachments) Delete(name string, options *meta_v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("awsiamgrouppolicyattachments").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *awsIamGroupPolicyAttachments) DeleteCollection(options *meta_v1.DeleteOptions, listOptions meta_v1.ListOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("awsiamgrouppolicyattachments").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched awsIamGroupPolicyAttachment.
func (c *awsIamGroupPolicyAttachments) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.AwsIamGroupPolicyAttachment, err error) {
	result = &v1.AwsIamGroupPolicyAttachment{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("awsiamgrouppolicyattachments").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
