/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	v1 "github.com/trussle/terraform-operator/pkg/apis/aws/v1"
	scheme "github.com/trussle/terraform-operator/pkg/client/clientset/versioned/scheme"
	meta_v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// AwsIotPoliciesGetter has a method to return a AwsIotPolicyInterface.
// A group's client should implement this interface.
type AwsIotPoliciesGetter interface {
	AwsIotPolicies(namespace string) AwsIotPolicyInterface
}

// AwsIotPolicyInterface has methods to work with AwsIotPolicy resources.
type AwsIotPolicyInterface interface {
	Create(*v1.AwsIotPolicy) (*v1.AwsIotPolicy, error)
	Update(*v1.AwsIotPolicy) (*v1.AwsIotPolicy, error)
	Delete(name string, options *meta_v1.DeleteOptions) error
	DeleteCollection(options *meta_v1.DeleteOptions, listOptions meta_v1.ListOptions) error
	Get(name string, options meta_v1.GetOptions) (*v1.AwsIotPolicy, error)
	List(opts meta_v1.ListOptions) (*v1.AwsIotPolicyList, error)
	Watch(opts meta_v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.AwsIotPolicy, err error)
	AwsIotPolicyExpansion
}

// awsIotPolicies implements AwsIotPolicyInterface
type awsIotPolicies struct {
	client rest.Interface
	ns     string
}

// newAwsIotPolicies returns a AwsIotPolicies
func newAwsIotPolicies(c *TrussleV1Client, namespace string) *awsIotPolicies {
	return &awsIotPolicies{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the awsIotPolicy, and returns the corresponding awsIotPolicy object, and an error if there is any.
func (c *awsIotPolicies) Get(name string, options meta_v1.GetOptions) (result *v1.AwsIotPolicy, err error) {
	result = &v1.AwsIotPolicy{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("awsiotpolicies").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of AwsIotPolicies that match those selectors.
func (c *awsIotPolicies) List(opts meta_v1.ListOptions) (result *v1.AwsIotPolicyList, err error) {
	result = &v1.AwsIotPolicyList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("awsiotpolicies").
		VersionedParams(&opts, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested awsIotPolicies.
func (c *awsIotPolicies) Watch(opts meta_v1.ListOptions) (watch.Interface, error) {
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("awsiotpolicies").
		VersionedParams(&opts, scheme.ParameterCodec).
		Watch()
}

// Create takes the representation of a awsIotPolicy and creates it.  Returns the server's representation of the awsIotPolicy, and an error, if there is any.
func (c *awsIotPolicies) Create(awsIotPolicy *v1.AwsIotPolicy) (result *v1.AwsIotPolicy, err error) {
	result = &v1.AwsIotPolicy{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("awsiotpolicies").
		Body(awsIotPolicy).
		Do().
		Into(result)
	return
}

// Update takes the representation of a awsIotPolicy and updates it. Returns the server's representation of the awsIotPolicy, and an error, if there is any.
func (c *awsIotPolicies) Update(awsIotPolicy *v1.AwsIotPolicy) (result *v1.AwsIotPolicy, err error) {
	result = &v1.AwsIotPolicy{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("awsiotpolicies").
		Name(awsIotPolicy.Name).
		Body(awsIotPolicy).
		Do().
		Into(result)
	return
}

// Delete takes name of the awsIotPolicy and deletes it. Returns an error if one occurs.
func (c *awsIotPolicies) Delete(name string, options *meta_v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("awsiotpolicies").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *awsIotPolicies) DeleteCollection(options *meta_v1.DeleteOptions, listOptions meta_v1.ListOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("awsiotpolicies").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched awsIotPolicy.
func (c *awsIotPolicies) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.AwsIotPolicy, err error) {
	result = &v1.AwsIotPolicy{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("awsiotpolicies").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
