/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	v1 "github.com/trussle/terraform-operator/pkg/apis/aws/v1"
	scheme "github.com/trussle/terraform-operator/pkg/client/clientset/versioned/scheme"
	meta_v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// AwsLoadBalancerListenerPoliciesGetter has a method to return a AwsLoadBalancerListenerPolicyInterface.
// A group's client should implement this interface.
type AwsLoadBalancerListenerPoliciesGetter interface {
	AwsLoadBalancerListenerPolicies(namespace string) AwsLoadBalancerListenerPolicyInterface
}

// AwsLoadBalancerListenerPolicyInterface has methods to work with AwsLoadBalancerListenerPolicy resources.
type AwsLoadBalancerListenerPolicyInterface interface {
	Create(*v1.AwsLoadBalancerListenerPolicy) (*v1.AwsLoadBalancerListenerPolicy, error)
	Update(*v1.AwsLoadBalancerListenerPolicy) (*v1.AwsLoadBalancerListenerPolicy, error)
	Delete(name string, options *meta_v1.DeleteOptions) error
	DeleteCollection(options *meta_v1.DeleteOptions, listOptions meta_v1.ListOptions) error
	Get(name string, options meta_v1.GetOptions) (*v1.AwsLoadBalancerListenerPolicy, error)
	List(opts meta_v1.ListOptions) (*v1.AwsLoadBalancerListenerPolicyList, error)
	Watch(opts meta_v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.AwsLoadBalancerListenerPolicy, err error)
	AwsLoadBalancerListenerPolicyExpansion
}

// awsLoadBalancerListenerPolicies implements AwsLoadBalancerListenerPolicyInterface
type awsLoadBalancerListenerPolicies struct {
	client rest.Interface
	ns     string
}

// newAwsLoadBalancerListenerPolicies returns a AwsLoadBalancerListenerPolicies
func newAwsLoadBalancerListenerPolicies(c *TrussleV1Client, namespace string) *awsLoadBalancerListenerPolicies {
	return &awsLoadBalancerListenerPolicies{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the awsLoadBalancerListenerPolicy, and returns the corresponding awsLoadBalancerListenerPolicy object, and an error if there is any.
func (c *awsLoadBalancerListenerPolicies) Get(name string, options meta_v1.GetOptions) (result *v1.AwsLoadBalancerListenerPolicy, err error) {
	result = &v1.AwsLoadBalancerListenerPolicy{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("awsloadbalancerlistenerpolicies").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of AwsLoadBalancerListenerPolicies that match those selectors.
func (c *awsLoadBalancerListenerPolicies) List(opts meta_v1.ListOptions) (result *v1.AwsLoadBalancerListenerPolicyList, err error) {
	result = &v1.AwsLoadBalancerListenerPolicyList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("awsloadbalancerlistenerpolicies").
		VersionedParams(&opts, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested awsLoadBalancerListenerPolicies.
func (c *awsLoadBalancerListenerPolicies) Watch(opts meta_v1.ListOptions) (watch.Interface, error) {
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("awsloadbalancerlistenerpolicies").
		VersionedParams(&opts, scheme.ParameterCodec).
		Watch()
}

// Create takes the representation of a awsLoadBalancerListenerPolicy and creates it.  Returns the server's representation of the awsLoadBalancerListenerPolicy, and an error, if there is any.
func (c *awsLoadBalancerListenerPolicies) Create(awsLoadBalancerListenerPolicy *v1.AwsLoadBalancerListenerPolicy) (result *v1.AwsLoadBalancerListenerPolicy, err error) {
	result = &v1.AwsLoadBalancerListenerPolicy{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("awsloadbalancerlistenerpolicies").
		Body(awsLoadBalancerListenerPolicy).
		Do().
		Into(result)
	return
}

// Update takes the representation of a awsLoadBalancerListenerPolicy and updates it. Returns the server's representation of the awsLoadBalancerListenerPolicy, and an error, if there is any.
func (c *awsLoadBalancerListenerPolicies) Update(awsLoadBalancerListenerPolicy *v1.AwsLoadBalancerListenerPolicy) (result *v1.AwsLoadBalancerListenerPolicy, err error) {
	result = &v1.AwsLoadBalancerListenerPolicy{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("awsloadbalancerlistenerpolicies").
		Name(awsLoadBalancerListenerPolicy.Name).
		Body(awsLoadBalancerListenerPolicy).
		Do().
		Into(result)
	return
}

// Delete takes name of the awsLoadBalancerListenerPolicy and deletes it. Returns an error if one occurs.
func (c *awsLoadBalancerListenerPolicies) Delete(name string, options *meta_v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("awsloadbalancerlistenerpolicies").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *awsLoadBalancerListenerPolicies) DeleteCollection(options *meta_v1.DeleteOptions, listOptions meta_v1.ListOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("awsloadbalancerlistenerpolicies").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched awsLoadBalancerListenerPolicy.
func (c *awsLoadBalancerListenerPolicies) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.AwsLoadBalancerListenerPolicy, err error) {
	result = &v1.AwsLoadBalancerListenerPolicy{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("awsloadbalancerlistenerpolicies").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
