/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	v1 "github.com/trussle/terraform-operator/pkg/apis/aws/v1"
	scheme "github.com/trussle/terraform-operator/pkg/client/clientset/versioned/scheme"
	meta_v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// AwsOpsworksJavaAppLayersGetter has a method to return a AwsOpsworksJavaAppLayerInterface.
// A group's client should implement this interface.
type AwsOpsworksJavaAppLayersGetter interface {
	AwsOpsworksJavaAppLayers(namespace string) AwsOpsworksJavaAppLayerInterface
}

// AwsOpsworksJavaAppLayerInterface has methods to work with AwsOpsworksJavaAppLayer resources.
type AwsOpsworksJavaAppLayerInterface interface {
	Create(*v1.AwsOpsworksJavaAppLayer) (*v1.AwsOpsworksJavaAppLayer, error)
	Update(*v1.AwsOpsworksJavaAppLayer) (*v1.AwsOpsworksJavaAppLayer, error)
	Delete(name string, options *meta_v1.DeleteOptions) error
	DeleteCollection(options *meta_v1.DeleteOptions, listOptions meta_v1.ListOptions) error
	Get(name string, options meta_v1.GetOptions) (*v1.AwsOpsworksJavaAppLayer, error)
	List(opts meta_v1.ListOptions) (*v1.AwsOpsworksJavaAppLayerList, error)
	Watch(opts meta_v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.AwsOpsworksJavaAppLayer, err error)
	AwsOpsworksJavaAppLayerExpansion
}

// awsOpsworksJavaAppLayers implements AwsOpsworksJavaAppLayerInterface
type awsOpsworksJavaAppLayers struct {
	client rest.Interface
	ns     string
}

// newAwsOpsworksJavaAppLayers returns a AwsOpsworksJavaAppLayers
func newAwsOpsworksJavaAppLayers(c *TrussleV1Client, namespace string) *awsOpsworksJavaAppLayers {
	return &awsOpsworksJavaAppLayers{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the awsOpsworksJavaAppLayer, and returns the corresponding awsOpsworksJavaAppLayer object, and an error if there is any.
func (c *awsOpsworksJavaAppLayers) Get(name string, options meta_v1.GetOptions) (result *v1.AwsOpsworksJavaAppLayer, err error) {
	result = &v1.AwsOpsworksJavaAppLayer{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("awsopsworksjavaapplayers").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of AwsOpsworksJavaAppLayers that match those selectors.
func (c *awsOpsworksJavaAppLayers) List(opts meta_v1.ListOptions) (result *v1.AwsOpsworksJavaAppLayerList, err error) {
	result = &v1.AwsOpsworksJavaAppLayerList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("awsopsworksjavaapplayers").
		VersionedParams(&opts, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested awsOpsworksJavaAppLayers.
func (c *awsOpsworksJavaAppLayers) Watch(opts meta_v1.ListOptions) (watch.Interface, error) {
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("awsopsworksjavaapplayers").
		VersionedParams(&opts, scheme.ParameterCodec).
		Watch()
}

// Create takes the representation of a awsOpsworksJavaAppLayer and creates it.  Returns the server's representation of the awsOpsworksJavaAppLayer, and an error, if there is any.
func (c *awsOpsworksJavaAppLayers) Create(awsOpsworksJavaAppLayer *v1.AwsOpsworksJavaAppLayer) (result *v1.AwsOpsworksJavaAppLayer, err error) {
	result = &v1.AwsOpsworksJavaAppLayer{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("awsopsworksjavaapplayers").
		Body(awsOpsworksJavaAppLayer).
		Do().
		Into(result)
	return
}

// Update takes the representation of a awsOpsworksJavaAppLayer and updates it. Returns the server's representation of the awsOpsworksJavaAppLayer, and an error, if there is any.
func (c *awsOpsworksJavaAppLayers) Update(awsOpsworksJavaAppLayer *v1.AwsOpsworksJavaAppLayer) (result *v1.AwsOpsworksJavaAppLayer, err error) {
	result = &v1.AwsOpsworksJavaAppLayer{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("awsopsworksjavaapplayers").
		Name(awsOpsworksJavaAppLayer.Name).
		Body(awsOpsworksJavaAppLayer).
		Do().
		Into(result)
	return
}

// Delete takes name of the awsOpsworksJavaAppLayer and deletes it. Returns an error if one occurs.
func (c *awsOpsworksJavaAppLayers) Delete(name string, options *meta_v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("awsopsworksjavaapplayers").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *awsOpsworksJavaAppLayers) DeleteCollection(options *meta_v1.DeleteOptions, listOptions meta_v1.ListOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("awsopsworksjavaapplayers").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched awsOpsworksJavaAppLayer.
func (c *awsOpsworksJavaAppLayers) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.AwsOpsworksJavaAppLayer, err error) {
	result = &v1.AwsOpsworksJavaAppLayer{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("awsopsworksjavaapplayers").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
