/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	v1 "github.com/trussle/terraform-operator/pkg/apis/aws/v1"
	scheme "github.com/trussle/terraform-operator/pkg/client/clientset/versioned/scheme"
	meta_v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// AwsPlacementGroupsGetter has a method to return a AwsPlacementGroupInterface.
// A group's client should implement this interface.
type AwsPlacementGroupsGetter interface {
	AwsPlacementGroups(namespace string) AwsPlacementGroupInterface
}

// AwsPlacementGroupInterface has methods to work with AwsPlacementGroup resources.
type AwsPlacementGroupInterface interface {
	Create(*v1.AwsPlacementGroup) (*v1.AwsPlacementGroup, error)
	Update(*v1.AwsPlacementGroup) (*v1.AwsPlacementGroup, error)
	Delete(name string, options *meta_v1.DeleteOptions) error
	DeleteCollection(options *meta_v1.DeleteOptions, listOptions meta_v1.ListOptions) error
	Get(name string, options meta_v1.GetOptions) (*v1.AwsPlacementGroup, error)
	List(opts meta_v1.ListOptions) (*v1.AwsPlacementGroupList, error)
	Watch(opts meta_v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.AwsPlacementGroup, err error)
	AwsPlacementGroupExpansion
}

// awsPlacementGroups implements AwsPlacementGroupInterface
type awsPlacementGroups struct {
	client rest.Interface
	ns     string
}

// newAwsPlacementGroups returns a AwsPlacementGroups
func newAwsPlacementGroups(c *TrussleV1Client, namespace string) *awsPlacementGroups {
	return &awsPlacementGroups{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the awsPlacementGroup, and returns the corresponding awsPlacementGroup object, and an error if there is any.
func (c *awsPlacementGroups) Get(name string, options meta_v1.GetOptions) (result *v1.AwsPlacementGroup, err error) {
	result = &v1.AwsPlacementGroup{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("awsplacementgroups").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of AwsPlacementGroups that match those selectors.
func (c *awsPlacementGroups) List(opts meta_v1.ListOptions) (result *v1.AwsPlacementGroupList, err error) {
	result = &v1.AwsPlacementGroupList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("awsplacementgroups").
		VersionedParams(&opts, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested awsPlacementGroups.
func (c *awsPlacementGroups) Watch(opts meta_v1.ListOptions) (watch.Interface, error) {
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("awsplacementgroups").
		VersionedParams(&opts, scheme.ParameterCodec).
		Watch()
}

// Create takes the representation of a awsPlacementGroup and creates it.  Returns the server's representation of the awsPlacementGroup, and an error, if there is any.
func (c *awsPlacementGroups) Create(awsPlacementGroup *v1.AwsPlacementGroup) (result *v1.AwsPlacementGroup, err error) {
	result = &v1.AwsPlacementGroup{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("awsplacementgroups").
		Body(awsPlacementGroup).
		Do().
		Into(result)
	return
}

// Update takes the representation of a awsPlacementGroup and updates it. Returns the server's representation of the awsPlacementGroup, and an error, if there is any.
func (c *awsPlacementGroups) Update(awsPlacementGroup *v1.AwsPlacementGroup) (result *v1.AwsPlacementGroup, err error) {
	result = &v1.AwsPlacementGroup{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("awsplacementgroups").
		Name(awsPlacementGroup.Name).
		Body(awsPlacementGroup).
		Do().
		Into(result)
	return
}

// Delete takes name of the awsPlacementGroup and deletes it. Returns an error if one occurs.
func (c *awsPlacementGroups) Delete(name string, options *meta_v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("awsplacementgroups").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *awsPlacementGroups) DeleteCollection(options *meta_v1.DeleteOptions, listOptions meta_v1.ListOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("awsplacementgroups").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched awsPlacementGroup.
func (c *awsPlacementGroups) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.AwsPlacementGroup, err error) {
	result = &v1.AwsPlacementGroup{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("awsplacementgroups").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
