/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	v1 "github.com/trussle/terraform-operator/pkg/apis/aws/v1"
	scheme "github.com/trussle/terraform-operator/pkg/client/clientset/versioned/scheme"
	meta_v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// AwsSsmPatchGroupsGetter has a method to return a AwsSsmPatchGroupInterface.
// A group's client should implement this interface.
type AwsSsmPatchGroupsGetter interface {
	AwsSsmPatchGroups(namespace string) AwsSsmPatchGroupInterface
}

// AwsSsmPatchGroupInterface has methods to work with AwsSsmPatchGroup resources.
type AwsSsmPatchGroupInterface interface {
	Create(*v1.AwsSsmPatchGroup) (*v1.AwsSsmPatchGroup, error)
	Update(*v1.AwsSsmPatchGroup) (*v1.AwsSsmPatchGroup, error)
	Delete(name string, options *meta_v1.DeleteOptions) error
	DeleteCollection(options *meta_v1.DeleteOptions, listOptions meta_v1.ListOptions) error
	Get(name string, options meta_v1.GetOptions) (*v1.AwsSsmPatchGroup, error)
	List(opts meta_v1.ListOptions) (*v1.AwsSsmPatchGroupList, error)
	Watch(opts meta_v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.AwsSsmPatchGroup, err error)
	AwsSsmPatchGroupExpansion
}

// awsSsmPatchGroups implements AwsSsmPatchGroupInterface
type awsSsmPatchGroups struct {
	client rest.Interface
	ns     string
}

// newAwsSsmPatchGroups returns a AwsSsmPatchGroups
func newAwsSsmPatchGroups(c *TrussleV1Client, namespace string) *awsSsmPatchGroups {
	return &awsSsmPatchGroups{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the awsSsmPatchGroup, and returns the corresponding awsSsmPatchGroup object, and an error if there is any.
func (c *awsSsmPatchGroups) Get(name string, options meta_v1.GetOptions) (result *v1.AwsSsmPatchGroup, err error) {
	result = &v1.AwsSsmPatchGroup{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("awsssmpatchgroups").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of AwsSsmPatchGroups that match those selectors.
func (c *awsSsmPatchGroups) List(opts meta_v1.ListOptions) (result *v1.AwsSsmPatchGroupList, err error) {
	result = &v1.AwsSsmPatchGroupList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("awsssmpatchgroups").
		VersionedParams(&opts, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested awsSsmPatchGroups.
func (c *awsSsmPatchGroups) Watch(opts meta_v1.ListOptions) (watch.Interface, error) {
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("awsssmpatchgroups").
		VersionedParams(&opts, scheme.ParameterCodec).
		Watch()
}

// Create takes the representation of a awsSsmPatchGroup and creates it.  Returns the server's representation of the awsSsmPatchGroup, and an error, if there is any.
func (c *awsSsmPatchGroups) Create(awsSsmPatchGroup *v1.AwsSsmPatchGroup) (result *v1.AwsSsmPatchGroup, err error) {
	result = &v1.AwsSsmPatchGroup{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("awsssmpatchgroups").
		Body(awsSsmPatchGroup).
		Do().
		Into(result)
	return
}

// Update takes the representation of a awsSsmPatchGroup and updates it. Returns the server's representation of the awsSsmPatchGroup, and an error, if there is any.
func (c *awsSsmPatchGroups) Update(awsSsmPatchGroup *v1.AwsSsmPatchGroup) (result *v1.AwsSsmPatchGroup, err error) {
	result = &v1.AwsSsmPatchGroup{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("awsssmpatchgroups").
		Name(awsSsmPatchGroup.Name).
		Body(awsSsmPatchGroup).
		Do().
		Into(result)
	return
}

// Delete takes name of the awsSsmPatchGroup and deletes it. Returns an error if one occurs.
func (c *awsSsmPatchGroups) Delete(name string, options *meta_v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("awsssmpatchgroups").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *awsSsmPatchGroups) DeleteCollection(options *meta_v1.DeleteOptions, listOptions meta_v1.ListOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("awsssmpatchgroups").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched awsSsmPatchGroup.
func (c *awsSsmPatchGroups) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.AwsSsmPatchGroup, err error) {
	result = &v1.AwsSsmPatchGroup{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("awsssmpatchgroups").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
