/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	v1 "github.com/trussle/terraform-operator/pkg/apis/aws/v1"
	scheme "github.com/trussle/terraform-operator/pkg/client/clientset/versioned/scheme"
	meta_v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// AwsSsmMaintenanceWindowTargetsGetter has a method to return a AwsSsmMaintenanceWindowTargetInterface.
// A group's client should implement this interface.
type AwsSsmMaintenanceWindowTargetsGetter interface {
	AwsSsmMaintenanceWindowTargets(namespace string) AwsSsmMaintenanceWindowTargetInterface
}

// AwsSsmMaintenanceWindowTargetInterface has methods to work with AwsSsmMaintenanceWindowTarget resources.
type AwsSsmMaintenanceWindowTargetInterface interface {
	Create(*v1.AwsSsmMaintenanceWindowTarget) (*v1.AwsSsmMaintenanceWindowTarget, error)
	Update(*v1.AwsSsmMaintenanceWindowTarget) (*v1.AwsSsmMaintenanceWindowTarget, error)
	Delete(name string, options *meta_v1.DeleteOptions) error
	DeleteCollection(options *meta_v1.DeleteOptions, listOptions meta_v1.ListOptions) error
	Get(name string, options meta_v1.GetOptions) (*v1.AwsSsmMaintenanceWindowTarget, error)
	List(opts meta_v1.ListOptions) (*v1.AwsSsmMaintenanceWindowTargetList, error)
	Watch(opts meta_v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.AwsSsmMaintenanceWindowTarget, err error)
	AwsSsmMaintenanceWindowTargetExpansion
}

// awsSsmMaintenanceWindowTargets implements AwsSsmMaintenanceWindowTargetInterface
type awsSsmMaintenanceWindowTargets struct {
	client rest.Interface
	ns     string
}

// newAwsSsmMaintenanceWindowTargets returns a AwsSsmMaintenanceWindowTargets
func newAwsSsmMaintenanceWindowTargets(c *TrussleV1Client, namespace string) *awsSsmMaintenanceWindowTargets {
	return &awsSsmMaintenanceWindowTargets{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the awsSsmMaintenanceWindowTarget, and returns the corresponding awsSsmMaintenanceWindowTarget object, and an error if there is any.
func (c *awsSsmMaintenanceWindowTargets) Get(name string, options meta_v1.GetOptions) (result *v1.AwsSsmMaintenanceWindowTarget, err error) {
	result = &v1.AwsSsmMaintenanceWindowTarget{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("awsssmmaintenancewindowtargets").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of AwsSsmMaintenanceWindowTargets that match those selectors.
func (c *awsSsmMaintenanceWindowTargets) List(opts meta_v1.ListOptions) (result *v1.AwsSsmMaintenanceWindowTargetList, err error) {
	result = &v1.AwsSsmMaintenanceWindowTargetList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("awsssmmaintenancewindowtargets").
		VersionedParams(&opts, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested awsSsmMaintenanceWindowTargets.
func (c *awsSsmMaintenanceWindowTargets) Watch(opts meta_v1.ListOptions) (watch.Interface, error) {
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("awsssmmaintenancewindowtargets").
		VersionedParams(&opts, scheme.ParameterCodec).
		Watch()
}

// Create takes the representation of a awsSsmMaintenanceWindowTarget and creates it.  Returns the server's representation of the awsSsmMaintenanceWindowTarget, and an error, if there is any.
func (c *awsSsmMaintenanceWindowTargets) Create(awsSsmMaintenanceWindowTarget *v1.AwsSsmMaintenanceWindowTarget) (result *v1.AwsSsmMaintenanceWindowTarget, err error) {
	result = &v1.AwsSsmMaintenanceWindowTarget{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("awsssmmaintenancewindowtargets").
		Body(awsSsmMaintenanceWindowTarget).
		Do().
		Into(result)
	return
}

// Update takes the representation of a awsSsmMaintenanceWindowTarget and updates it. Returns the server's representation of the awsSsmMaintenanceWindowTarget, and an error, if there is any.
func (c *awsSsmMaintenanceWindowTargets) Update(awsSsmMaintenanceWindowTarget *v1.AwsSsmMaintenanceWindowTarget) (result *v1.AwsSsmMaintenanceWindowTarget, err error) {
	result = &v1.AwsSsmMaintenanceWindowTarget{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("awsssmmaintenancewindowtargets").
		Name(awsSsmMaintenanceWindowTarget.Name).
		Body(awsSsmMaintenanceWindowTarget).
		Do().
		Into(result)
	return
}

// Delete takes name of the awsSsmMaintenanceWindowTarget and deletes it. Returns an error if one occurs.
func (c *awsSsmMaintenanceWindowTargets) Delete(name string, options *meta_v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("awsssmmaintenancewindowtargets").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *awsSsmMaintenanceWindowTargets) DeleteCollection(options *meta_v1.DeleteOptions, listOptions meta_v1.ListOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("awsssmmaintenancewindowtargets").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched awsSsmMaintenanceWindowTarget.
func (c *awsSsmMaintenanceWindowTargets) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.AwsSsmMaintenanceWindowTarget, err error) {
	result = &v1.AwsSsmMaintenanceWindowTarget{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("awsssmmaintenancewindowtargets").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
