/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	v1 "github.com/trussle/terraform-operator/pkg/apis/aws/v1"
	scheme "github.com/trussle/terraform-operator/pkg/client/clientset/versioned/scheme"
	meta_v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// AwsSsmDocumentsGetter has a method to return a AwsSsmDocumentInterface.
// A group's client should implement this interface.
type AwsSsmDocumentsGetter interface {
	AwsSsmDocuments(namespace string) AwsSsmDocumentInterface
}

// AwsSsmDocumentInterface has methods to work with AwsSsmDocument resources.
type AwsSsmDocumentInterface interface {
	Create(*v1.AwsSsmDocument) (*v1.AwsSsmDocument, error)
	Update(*v1.AwsSsmDocument) (*v1.AwsSsmDocument, error)
	Delete(name string, options *meta_v1.DeleteOptions) error
	DeleteCollection(options *meta_v1.DeleteOptions, listOptions meta_v1.ListOptions) error
	Get(name string, options meta_v1.GetOptions) (*v1.AwsSsmDocument, error)
	List(opts meta_v1.ListOptions) (*v1.AwsSsmDocumentList, error)
	Watch(opts meta_v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.AwsSsmDocument, err error)
	AwsSsmDocumentExpansion
}

// awsSsmDocuments implements AwsSsmDocumentInterface
type awsSsmDocuments struct {
	client rest.Interface
	ns     string
}

// newAwsSsmDocuments returns a AwsSsmDocuments
func newAwsSsmDocuments(c *TrussleV1Client, namespace string) *awsSsmDocuments {
	return &awsSsmDocuments{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the awsSsmDocument, and returns the corresponding awsSsmDocument object, and an error if there is any.
func (c *awsSsmDocuments) Get(name string, options meta_v1.GetOptions) (result *v1.AwsSsmDocument, err error) {
	result = &v1.AwsSsmDocument{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("awsssmdocuments").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of AwsSsmDocuments that match those selectors.
func (c *awsSsmDocuments) List(opts meta_v1.ListOptions) (result *v1.AwsSsmDocumentList, err error) {
	result = &v1.AwsSsmDocumentList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("awsssmdocuments").
		VersionedParams(&opts, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested awsSsmDocuments.
func (c *awsSsmDocuments) Watch(opts meta_v1.ListOptions) (watch.Interface, error) {
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("awsssmdocuments").
		VersionedParams(&opts, scheme.ParameterCodec).
		Watch()
}

// Create takes the representation of a awsSsmDocument and creates it.  Returns the server's representation of the awsSsmDocument, and an error, if there is any.
func (c *awsSsmDocuments) Create(awsSsmDocument *v1.AwsSsmDocument) (result *v1.AwsSsmDocument, err error) {
	result = &v1.AwsSsmDocument{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("awsssmdocuments").
		Body(awsSsmDocument).
		Do().
		Into(result)
	return
}

// Update takes the representation of a awsSsmDocument and updates it. Returns the server's representation of the awsSsmDocument, and an error, if there is any.
func (c *awsSsmDocuments) Update(awsSsmDocument *v1.AwsSsmDocument) (result *v1.AwsSsmDocument, err error) {
	result = &v1.AwsSsmDocument{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("awsssmdocuments").
		Name(awsSsmDocument.Name).
		Body(awsSsmDocument).
		Do().
		Into(result)
	return
}

// Delete takes name of the awsSsmDocument and deletes it. Returns an error if one occurs.
func (c *awsSsmDocuments) Delete(name string, options *meta_v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("awsssmdocuments").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *awsSsmDocuments) DeleteCollection(options *meta_v1.DeleteOptions, listOptions meta_v1.ListOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("awsssmdocuments").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched awsSsmDocument.
func (c *awsSsmDocuments) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.AwsSsmDocument, err error) {
	result = &v1.AwsSsmDocument{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("awsssmdocuments").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
