/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1

import (
	v1 "github.com/trussle/terraform-operator/pkg/apis/aws/v1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// AwsCloudwatchLogStreamLister helps list AwsCloudwatchLogStreams.
type AwsCloudwatchLogStreamLister interface {
	// List lists all AwsCloudwatchLogStreams in the indexer.
	List(selector labels.Selector) (ret []*v1.AwsCloudwatchLogStream, err error)
	// AwsCloudwatchLogStreams returns an object that can list and get AwsCloudwatchLogStreams.
	AwsCloudwatchLogStreams(namespace string) AwsCloudwatchLogStreamNamespaceLister
	AwsCloudwatchLogStreamListerExpansion
}

// awsCloudwatchLogStreamLister implements the AwsCloudwatchLogStreamLister interface.
type awsCloudwatchLogStreamLister struct {
	indexer cache.Indexer
}

// NewAwsCloudwatchLogStreamLister returns a new AwsCloudwatchLogStreamLister.
func NewAwsCloudwatchLogStreamLister(indexer cache.Indexer) AwsCloudwatchLogStreamLister {
	return &awsCloudwatchLogStreamLister{indexer: indexer}
}

// List lists all AwsCloudwatchLogStreams in the indexer.
func (s *awsCloudwatchLogStreamLister) List(selector labels.Selector) (ret []*v1.AwsCloudwatchLogStream, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1.AwsCloudwatchLogStream))
	})
	return ret, err
}

// AwsCloudwatchLogStreams returns an object that can list and get AwsCloudwatchLogStreams.
func (s *awsCloudwatchLogStreamLister) AwsCloudwatchLogStreams(namespace string) AwsCloudwatchLogStreamNamespaceLister {
	return awsCloudwatchLogStreamNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// AwsCloudwatchLogStreamNamespaceLister helps list and get AwsCloudwatchLogStreams.
type AwsCloudwatchLogStreamNamespaceLister interface {
	// List lists all AwsCloudwatchLogStreams in the indexer for a given namespace.
	List(selector labels.Selector) (ret []*v1.AwsCloudwatchLogStream, err error)
	// Get retrieves the AwsCloudwatchLogStream from the indexer for a given namespace and name.
	Get(name string) (*v1.AwsCloudwatchLogStream, error)
	AwsCloudwatchLogStreamNamespaceListerExpansion
}

// awsCloudwatchLogStreamNamespaceLister implements the AwsCloudwatchLogStreamNamespaceLister
// interface.
type awsCloudwatchLogStreamNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all AwsCloudwatchLogStreams in the indexer for a given namespace.
func (s awsCloudwatchLogStreamNamespaceLister) List(selector labels.Selector) (ret []*v1.AwsCloudwatchLogStream, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*v1.AwsCloudwatchLogStream))
	})
	return ret, err
}

// Get retrieves the AwsCloudwatchLogStream from the indexer for a given namespace and name.
func (s awsCloudwatchLogStreamNamespaceLister) Get(name string) (*v1.AwsCloudwatchLogStream, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1.Resource("awscloudwatchlogstream"), name)
	}
	return obj.(*v1.AwsCloudwatchLogStream), nil
}
