/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1

import (
	v1 "github.com/trussle/terraform-operator/pkg/apis/aws/v1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// AwsDbSnapshotLister helps list AwsDbSnapshots.
type AwsDbSnapshotLister interface {
	// List lists all AwsDbSnapshots in the indexer.
	List(selector labels.Selector) (ret []*v1.AwsDbSnapshot, err error)
	// AwsDbSnapshots returns an object that can list and get AwsDbSnapshots.
	AwsDbSnapshots(namespace string) AwsDbSnapshotNamespaceLister
	AwsDbSnapshotListerExpansion
}

// awsDbSnapshotLister implements the AwsDbSnapshotLister interface.
type awsDbSnapshotLister struct {
	indexer cache.Indexer
}

// NewAwsDbSnapshotLister returns a new AwsDbSnapshotLister.
func NewAwsDbSnapshotLister(indexer cache.Indexer) AwsDbSnapshotLister {
	return &awsDbSnapshotLister{indexer: indexer}
}

// List lists all AwsDbSnapshots in the indexer.
func (s *awsDbSnapshotLister) List(selector labels.Selector) (ret []*v1.AwsDbSnapshot, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1.AwsDbSnapshot))
	})
	return ret, err
}

// AwsDbSnapshots returns an object that can list and get AwsDbSnapshots.
func (s *awsDbSnapshotLister) AwsDbSnapshots(namespace string) AwsDbSnapshotNamespaceLister {
	return awsDbSnapshotNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// AwsDbSnapshotNamespaceLister helps list and get AwsDbSnapshots.
type AwsDbSnapshotNamespaceLister interface {
	// List lists all AwsDbSnapshots in the indexer for a given namespace.
	List(selector labels.Selector) (ret []*v1.AwsDbSnapshot, err error)
	// Get retrieves the AwsDbSnapshot from the indexer for a given namespace and name.
	Get(name string) (*v1.AwsDbSnapshot, error)
	AwsDbSnapshotNamespaceListerExpansion
}

// awsDbSnapshotNamespaceLister implements the AwsDbSnapshotNamespaceLister
// interface.
type awsDbSnapshotNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all AwsDbSnapshots in the indexer for a given namespace.
func (s awsDbSnapshotNamespaceLister) List(selector labels.Selector) (ret []*v1.AwsDbSnapshot, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*v1.AwsDbSnapshot))
	})
	return ret, err
}

// Get retrieves the AwsDbSnapshot from the indexer for a given namespace and name.
func (s awsDbSnapshotNamespaceLister) Get(name string) (*v1.AwsDbSnapshot, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1.Resource("awsdbsnapshot"), name)
	}
	return obj.(*v1.AwsDbSnapshot), nil
}
