/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1

import (
	v1 "github.com/trussle/terraform-operator/pkg/apis/aws/v1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// AwsGuarddutyThreatintelsetLister helps list AwsGuarddutyThreatintelsets.
type AwsGuarddutyThreatintelsetLister interface {
	// List lists all AwsGuarddutyThreatintelsets in the indexer.
	List(selector labels.Selector) (ret []*v1.AwsGuarddutyThreatintelset, err error)
	// AwsGuarddutyThreatintelsets returns an object that can list and get AwsGuarddutyThreatintelsets.
	AwsGuarddutyThreatintelsets(namespace string) AwsGuarddutyThreatintelsetNamespaceLister
	AwsGuarddutyThreatintelsetListerExpansion
}

// awsGuarddutyThreatintelsetLister implements the AwsGuarddutyThreatintelsetLister interface.
type awsGuarddutyThreatintelsetLister struct {
	indexer cache.Indexer
}

// NewAwsGuarddutyThreatintelsetLister returns a new AwsGuarddutyThreatintelsetLister.
func NewAwsGuarddutyThreatintelsetLister(indexer cache.Indexer) AwsGuarddutyThreatintelsetLister {
	return &awsGuarddutyThreatintelsetLister{indexer: indexer}
}

// List lists all AwsGuarddutyThreatintelsets in the indexer.
func (s *awsGuarddutyThreatintelsetLister) List(selector labels.Selector) (ret []*v1.AwsGuarddutyThreatintelset, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1.AwsGuarddutyThreatintelset))
	})
	return ret, err
}

// AwsGuarddutyThreatintelsets returns an object that can list and get AwsGuarddutyThreatintelsets.
func (s *awsGuarddutyThreatintelsetLister) AwsGuarddutyThreatintelsets(namespace string) AwsGuarddutyThreatintelsetNamespaceLister {
	return awsGuarddutyThreatintelsetNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// AwsGuarddutyThreatintelsetNamespaceLister helps list and get AwsGuarddutyThreatintelsets.
type AwsGuarddutyThreatintelsetNamespaceLister interface {
	// List lists all AwsGuarddutyThreatintelsets in the indexer for a given namespace.
	List(selector labels.Selector) (ret []*v1.AwsGuarddutyThreatintelset, err error)
	// Get retrieves the AwsGuarddutyThreatintelset from the indexer for a given namespace and name.
	Get(name string) (*v1.AwsGuarddutyThreatintelset, error)
	AwsGuarddutyThreatintelsetNamespaceListerExpansion
}

// awsGuarddutyThreatintelsetNamespaceLister implements the AwsGuarddutyThreatintelsetNamespaceLister
// interface.
type awsGuarddutyThreatintelsetNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all AwsGuarddutyThreatintelsets in the indexer for a given namespace.
func (s awsGuarddutyThreatintelsetNamespaceLister) List(selector labels.Selector) (ret []*v1.AwsGuarddutyThreatintelset, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*v1.AwsGuarddutyThreatintelset))
	})
	return ret, err
}

// Get retrieves the AwsGuarddutyThreatintelset from the indexer for a given namespace and name.
func (s awsGuarddutyThreatintelsetNamespaceLister) Get(name string) (*v1.AwsGuarddutyThreatintelset, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1.Resource("awsguarddutythreatintelset"), name)
	}
	return obj.(*v1.AwsGuarddutyThreatintelset), nil
}
