/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1

import (
	v1 "github.com/trussle/terraform-operator/pkg/apis/aws/v1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// AwsLambdaFunctionLister helps list AwsLambdaFunctions.
type AwsLambdaFunctionLister interface {
	// List lists all AwsLambdaFunctions in the indexer.
	List(selector labels.Selector) (ret []*v1.AwsLambdaFunction, err error)
	// AwsLambdaFunctions returns an object that can list and get AwsLambdaFunctions.
	AwsLambdaFunctions(namespace string) AwsLambdaFunctionNamespaceLister
	AwsLambdaFunctionListerExpansion
}

// awsLambdaFunctionLister implements the AwsLambdaFunctionLister interface.
type awsLambdaFunctionLister struct {
	indexer cache.Indexer
}

// NewAwsLambdaFunctionLister returns a new AwsLambdaFunctionLister.
func NewAwsLambdaFunctionLister(indexer cache.Indexer) AwsLambdaFunctionLister {
	return &awsLambdaFunctionLister{indexer: indexer}
}

// List lists all AwsLambdaFunctions in the indexer.
func (s *awsLambdaFunctionLister) List(selector labels.Selector) (ret []*v1.AwsLambdaFunction, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1.AwsLambdaFunction))
	})
	return ret, err
}

// AwsLambdaFunctions returns an object that can list and get AwsLambdaFunctions.
func (s *awsLambdaFunctionLister) AwsLambdaFunctions(namespace string) AwsLambdaFunctionNamespaceLister {
	return awsLambdaFunctionNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// AwsLambdaFunctionNamespaceLister helps list and get AwsLambdaFunctions.
type AwsLambdaFunctionNamespaceLister interface {
	// List lists all AwsLambdaFunctions in the indexer for a given namespace.
	List(selector labels.Selector) (ret []*v1.AwsLambdaFunction, err error)
	// Get retrieves the AwsLambdaFunction from the indexer for a given namespace and name.
	Get(name string) (*v1.AwsLambdaFunction, error)
	AwsLambdaFunctionNamespaceListerExpansion
}

// awsLambdaFunctionNamespaceLister implements the AwsLambdaFunctionNamespaceLister
// interface.
type awsLambdaFunctionNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all AwsLambdaFunctions in the indexer for a given namespace.
func (s awsLambdaFunctionNamespaceLister) List(selector labels.Selector) (ret []*v1.AwsLambdaFunction, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*v1.AwsLambdaFunction))
	})
	return ret, err
}

// Get retrieves the AwsLambdaFunction from the indexer for a given namespace and name.
func (s awsLambdaFunctionNamespaceLister) Get(name string) (*v1.AwsLambdaFunction, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1.Resource("awslambdafunction"), name)
	}
	return obj.(*v1.AwsLambdaFunction), nil
}
