/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1

import (
	v1 "github.com/trussle/terraform-operator/pkg/apis/aws/v1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// AwsVpnConnectionRouteLister helps list AwsVpnConnectionRoutes.
type AwsVpnConnectionRouteLister interface {
	// List lists all AwsVpnConnectionRoutes in the indexer.
	List(selector labels.Selector) (ret []*v1.AwsVpnConnectionRoute, err error)
	// AwsVpnConnectionRoutes returns an object that can list and get AwsVpnConnectionRoutes.
	AwsVpnConnectionRoutes(namespace string) AwsVpnConnectionRouteNamespaceLister
	AwsVpnConnectionRouteListerExpansion
}

// awsVpnConnectionRouteLister implements the AwsVpnConnectionRouteLister interface.
type awsVpnConnectionRouteLister struct {
	indexer cache.Indexer
}

// NewAwsVpnConnectionRouteLister returns a new AwsVpnConnectionRouteLister.
func NewAwsVpnConnectionRouteLister(indexer cache.Indexer) AwsVpnConnectionRouteLister {
	return &awsVpnConnectionRouteLister{indexer: indexer}
}

// List lists all AwsVpnConnectionRoutes in the indexer.
func (s *awsVpnConnectionRouteLister) List(selector labels.Selector) (ret []*v1.AwsVpnConnectionRoute, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1.AwsVpnConnectionRoute))
	})
	return ret, err
}

// AwsVpnConnectionRoutes returns an object that can list and get AwsVpnConnectionRoutes.
func (s *awsVpnConnectionRouteLister) AwsVpnConnectionRoutes(namespace string) AwsVpnConnectionRouteNamespaceLister {
	return awsVpnConnectionRouteNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// AwsVpnConnectionRouteNamespaceLister helps list and get AwsVpnConnectionRoutes.
type AwsVpnConnectionRouteNamespaceLister interface {
	// List lists all AwsVpnConnectionRoutes in the indexer for a given namespace.
	List(selector labels.Selector) (ret []*v1.AwsVpnConnectionRoute, err error)
	// Get retrieves the AwsVpnConnectionRoute from the indexer for a given namespace and name.
	Get(name string) (*v1.AwsVpnConnectionRoute, error)
	AwsVpnConnectionRouteNamespaceListerExpansion
}

// awsVpnConnectionRouteNamespaceLister implements the AwsVpnConnectionRouteNamespaceLister
// interface.
type awsVpnConnectionRouteNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all AwsVpnConnectionRoutes in the indexer for a given namespace.
func (s awsVpnConnectionRouteNamespaceLister) List(selector labels.Selector) (ret []*v1.AwsVpnConnectionRoute, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*v1.AwsVpnConnectionRoute))
	})
	return ret, err
}

// Get retrieves the AwsVpnConnectionRoute from the indexer for a given namespace and name.
func (s awsVpnConnectionRouteNamespaceLister) Get(name string) (*v1.AwsVpnConnectionRoute, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1.Resource("awsvpnconnectionroute"), name)
	}
	return obj.(*v1.AwsVpnConnectionRoute), nil
}
