/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	aws_v1 "github.com/trussle/terraform-operator/pkg/apis/aws/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeAwsS3BucketPolicies implements AwsS3BucketPolicyInterface
type FakeAwsS3BucketPolicies struct {
	Fake *FakeTrussleV1
	ns   string
}

var awss3bucketpoliciesResource = schema.GroupVersionResource{Group: "trussle.com", Version: "v1", Resource: "awss3bucketpolicies"}

var awss3bucketpoliciesKind = schema.GroupVersionKind{Group: "trussle.com", Version: "v1", Kind: "AwsS3BucketPolicy"}

// Get takes name of the awsS3BucketPolicy, and returns the corresponding awsS3BucketPolicy object, and an error if there is any.
func (c *FakeAwsS3BucketPolicies) Get(name string, options v1.GetOptions) (result *aws_v1.AwsS3BucketPolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(awss3bucketpoliciesResource, c.ns, name), &aws_v1.AwsS3BucketPolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*aws_v1.AwsS3BucketPolicy), err
}

// List takes label and field selectors, and returns the list of AwsS3BucketPolicies that match those selectors.
func (c *FakeAwsS3BucketPolicies) List(opts v1.ListOptions) (result *aws_v1.AwsS3BucketPolicyList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(awss3bucketpoliciesResource, awss3bucketpoliciesKind, c.ns, opts), &aws_v1.AwsS3BucketPolicyList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &aws_v1.AwsS3BucketPolicyList{}
	for _, item := range obj.(*aws_v1.AwsS3BucketPolicyList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested awsS3BucketPolicies.
func (c *FakeAwsS3BucketPolicies) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(awss3bucketpoliciesResource, c.ns, opts))

}

// Create takes the representation of a awsS3BucketPolicy and creates it.  Returns the server's representation of the awsS3BucketPolicy, and an error, if there is any.
func (c *FakeAwsS3BucketPolicies) Create(awsS3BucketPolicy *aws_v1.AwsS3BucketPolicy) (result *aws_v1.AwsS3BucketPolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(awss3bucketpoliciesResource, c.ns, awsS3BucketPolicy), &aws_v1.AwsS3BucketPolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*aws_v1.AwsS3BucketPolicy), err
}

// Update takes the representation of a awsS3BucketPolicy and updates it. Returns the server's representation of the awsS3BucketPolicy, and an error, if there is any.
func (c *FakeAwsS3BucketPolicies) Update(awsS3BucketPolicy *aws_v1.AwsS3BucketPolicy) (result *aws_v1.AwsS3BucketPolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(awss3bucketpoliciesResource, c.ns, awsS3BucketPolicy), &aws_v1.AwsS3BucketPolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*aws_v1.AwsS3BucketPolicy), err
}

// Delete takes name of the awsS3BucketPolicy and deletes it. Returns an error if one occurs.
func (c *FakeAwsS3BucketPolicies) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(awss3bucketpoliciesResource, c.ns, name), &aws_v1.AwsS3BucketPolicy{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeAwsS3BucketPolicies) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(awss3bucketpoliciesResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &aws_v1.AwsS3BucketPolicyList{})
	return err
}

// Patch applies the patch and returns the patched awsS3BucketPolicy.
func (c *FakeAwsS3BucketPolicies) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *aws_v1.AwsS3BucketPolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(awss3bucketpoliciesResource, c.ns, name, data, subresources...), &aws_v1.AwsS3BucketPolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*aws_v1.AwsS3BucketPolicy), err
}
