/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	aws_v1 "github.com/trussle/terraform-operator/pkg/apis/aws/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeAwsSesReceiptRules implements AwsSesReceiptRuleInterface
type FakeAwsSesReceiptRules struct {
	Fake *FakeTrussleV1
	ns   string
}

var awssesreceiptrulesResource = schema.GroupVersionResource{Group: "trussle.com", Version: "v1", Resource: "awssesreceiptrules"}

var awssesreceiptrulesKind = schema.GroupVersionKind{Group: "trussle.com", Version: "v1", Kind: "AwsSesReceiptRule"}

// Get takes name of the awsSesReceiptRule, and returns the corresponding awsSesReceiptRule object, and an error if there is any.
func (c *FakeAwsSesReceiptRules) Get(name string, options v1.GetOptions) (result *aws_v1.AwsSesReceiptRule, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(awssesreceiptrulesResource, c.ns, name), &aws_v1.AwsSesReceiptRule{})

	if obj == nil {
		return nil, err
	}
	return obj.(*aws_v1.AwsSesReceiptRule), err
}

// List takes label and field selectors, and returns the list of AwsSesReceiptRules that match those selectors.
func (c *FakeAwsSesReceiptRules) List(opts v1.ListOptions) (result *aws_v1.AwsSesReceiptRuleList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(awssesreceiptrulesResource, awssesreceiptrulesKind, c.ns, opts), &aws_v1.AwsSesReceiptRuleList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &aws_v1.AwsSesReceiptRuleList{}
	for _, item := range obj.(*aws_v1.AwsSesReceiptRuleList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested awsSesReceiptRules.
func (c *FakeAwsSesReceiptRules) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(awssesreceiptrulesResource, c.ns, opts))

}

// Create takes the representation of a awsSesReceiptRule and creates it.  Returns the server's representation of the awsSesReceiptRule, and an error, if there is any.
func (c *FakeAwsSesReceiptRules) Create(awsSesReceiptRule *aws_v1.AwsSesReceiptRule) (result *aws_v1.AwsSesReceiptRule, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(awssesreceiptrulesResource, c.ns, awsSesReceiptRule), &aws_v1.AwsSesReceiptRule{})

	if obj == nil {
		return nil, err
	}
	return obj.(*aws_v1.AwsSesReceiptRule), err
}

// Update takes the representation of a awsSesReceiptRule and updates it. Returns the server's representation of the awsSesReceiptRule, and an error, if there is any.
func (c *FakeAwsSesReceiptRules) Update(awsSesReceiptRule *aws_v1.AwsSesReceiptRule) (result *aws_v1.AwsSesReceiptRule, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(awssesreceiptrulesResource, c.ns, awsSesReceiptRule), &aws_v1.AwsSesReceiptRule{})

	if obj == nil {
		return nil, err
	}
	return obj.(*aws_v1.AwsSesReceiptRule), err
}

// Delete takes name of the awsSesReceiptRule and deletes it. Returns an error if one occurs.
func (c *FakeAwsSesReceiptRules) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(awssesreceiptrulesResource, c.ns, name), &aws_v1.AwsSesReceiptRule{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeAwsSesReceiptRules) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(awssesreceiptrulesResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &aws_v1.AwsSesReceiptRuleList{})
	return err
}

// Patch applies the patch and returns the patched awsSesReceiptRule.
func (c *FakeAwsSesReceiptRules) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *aws_v1.AwsSesReceiptRule, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(awssesreceiptrulesResource, c.ns, name, data, subresources...), &aws_v1.AwsSesReceiptRule{})

	if obj == nil {
		return nil, err
	}
	return obj.(*aws_v1.AwsSesReceiptRule), err
}
