/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	aws_v1 "github.com/trussle/terraform-operator/pkg/apis/aws/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeAwsDbParameterGroups implements AwsDbParameterGroupInterface
type FakeAwsDbParameterGroups struct {
	Fake *FakeTrussleV1
	ns   string
}

var awsdbparametergroupsResource = schema.GroupVersionResource{Group: "trussle.com", Version: "v1", Resource: "awsdbparametergroups"}

var awsdbparametergroupsKind = schema.GroupVersionKind{Group: "trussle.com", Version: "v1", Kind: "AwsDbParameterGroup"}

// Get takes name of the awsDbParameterGroup, and returns the corresponding awsDbParameterGroup object, and an error if there is any.
func (c *FakeAwsDbParameterGroups) Get(name string, options v1.GetOptions) (result *aws_v1.AwsDbParameterGroup, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(awsdbparametergroupsResource, c.ns, name), &aws_v1.AwsDbParameterGroup{})

	if obj == nil {
		return nil, err
	}
	return obj.(*aws_v1.AwsDbParameterGroup), err
}

// List takes label and field selectors, and returns the list of AwsDbParameterGroups that match those selectors.
func (c *FakeAwsDbParameterGroups) List(opts v1.ListOptions) (result *aws_v1.AwsDbParameterGroupList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(awsdbparametergroupsResource, awsdbparametergroupsKind, c.ns, opts), &aws_v1.AwsDbParameterGroupList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &aws_v1.AwsDbParameterGroupList{}
	for _, item := range obj.(*aws_v1.AwsDbParameterGroupList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested awsDbParameterGroups.
func (c *FakeAwsDbParameterGroups) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(awsdbparametergroupsResource, c.ns, opts))

}

// Create takes the representation of a awsDbParameterGroup and creates it.  Returns the server's representation of the awsDbParameterGroup, and an error, if there is any.
func (c *FakeAwsDbParameterGroups) Create(awsDbParameterGroup *aws_v1.AwsDbParameterGroup) (result *aws_v1.AwsDbParameterGroup, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(awsdbparametergroupsResource, c.ns, awsDbParameterGroup), &aws_v1.AwsDbParameterGroup{})

	if obj == nil {
		return nil, err
	}
	return obj.(*aws_v1.AwsDbParameterGroup), err
}

// Update takes the representation of a awsDbParameterGroup and updates it. Returns the server's representation of the awsDbParameterGroup, and an error, if there is any.
func (c *FakeAwsDbParameterGroups) Update(awsDbParameterGroup *aws_v1.AwsDbParameterGroup) (result *aws_v1.AwsDbParameterGroup, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(awsdbparametergroupsResource, c.ns, awsDbParameterGroup), &aws_v1.AwsDbParameterGroup{})

	if obj == nil {
		return nil, err
	}
	return obj.(*aws_v1.AwsDbParameterGroup), err
}

// Delete takes name of the awsDbParameterGroup and deletes it. Returns an error if one occurs.
func (c *FakeAwsDbParameterGroups) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(awsdbparametergroupsResource, c.ns, name), &aws_v1.AwsDbParameterGroup{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeAwsDbParameterGroups) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(awsdbparametergroupsResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &aws_v1.AwsDbParameterGroupList{})
	return err
}

// Patch applies the patch and returns the patched awsDbParameterGroup.
func (c *FakeAwsDbParameterGroups) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *aws_v1.AwsDbParameterGroup, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(awsdbparametergroupsResource, c.ns, name, data, subresources...), &aws_v1.AwsDbParameterGroup{})

	if obj == nil {
		return nil, err
	}
	return obj.(*aws_v1.AwsDbParameterGroup), err
}
