/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	aws_v1 "github.com/trussle/terraform-operator/pkg/apis/aws/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeAwsRoute53QueryLogs implements AwsRoute53QueryLogInterface
type FakeAwsRoute53QueryLogs struct {
	Fake *FakeTrussleV1
	ns   string
}

var awsroute53querylogsResource = schema.GroupVersionResource{Group: "trussle.com", Version: "v1", Resource: "awsroute53querylogs"}

var awsroute53querylogsKind = schema.GroupVersionKind{Group: "trussle.com", Version: "v1", Kind: "AwsRoute53QueryLog"}

// Get takes name of the awsRoute53QueryLog, and returns the corresponding awsRoute53QueryLog object, and an error if there is any.
func (c *FakeAwsRoute53QueryLogs) Get(name string, options v1.GetOptions) (result *aws_v1.AwsRoute53QueryLog, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(awsroute53querylogsResource, c.ns, name), &aws_v1.AwsRoute53QueryLog{})

	if obj == nil {
		return nil, err
	}
	return obj.(*aws_v1.AwsRoute53QueryLog), err
}

// List takes label and field selectors, and returns the list of AwsRoute53QueryLogs that match those selectors.
func (c *FakeAwsRoute53QueryLogs) List(opts v1.ListOptions) (result *aws_v1.AwsRoute53QueryLogList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(awsroute53querylogsResource, awsroute53querylogsKind, c.ns, opts), &aws_v1.AwsRoute53QueryLogList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &aws_v1.AwsRoute53QueryLogList{}
	for _, item := range obj.(*aws_v1.AwsRoute53QueryLogList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested awsRoute53QueryLogs.
func (c *FakeAwsRoute53QueryLogs) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(awsroute53querylogsResource, c.ns, opts))

}

// Create takes the representation of a awsRoute53QueryLog and creates it.  Returns the server's representation of the awsRoute53QueryLog, and an error, if there is any.
func (c *FakeAwsRoute53QueryLogs) Create(awsRoute53QueryLog *aws_v1.AwsRoute53QueryLog) (result *aws_v1.AwsRoute53QueryLog, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(awsroute53querylogsResource, c.ns, awsRoute53QueryLog), &aws_v1.AwsRoute53QueryLog{})

	if obj == nil {
		return nil, err
	}
	return obj.(*aws_v1.AwsRoute53QueryLog), err
}

// Update takes the representation of a awsRoute53QueryLog and updates it. Returns the server's representation of the awsRoute53QueryLog, and an error, if there is any.
func (c *FakeAwsRoute53QueryLogs) Update(awsRoute53QueryLog *aws_v1.AwsRoute53QueryLog) (result *aws_v1.AwsRoute53QueryLog, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(awsroute53querylogsResource, c.ns, awsRoute53QueryLog), &aws_v1.AwsRoute53QueryLog{})

	if obj == nil {
		return nil, err
	}
	return obj.(*aws_v1.AwsRoute53QueryLog), err
}

// Delete takes name of the awsRoute53QueryLog and deletes it. Returns an error if one occurs.
func (c *FakeAwsRoute53QueryLogs) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(awsroute53querylogsResource, c.ns, name), &aws_v1.AwsRoute53QueryLog{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeAwsRoute53QueryLogs) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(awsroute53querylogsResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &aws_v1.AwsRoute53QueryLogList{})
	return err
}

// Patch applies the patch and returns the patched awsRoute53QueryLog.
func (c *FakeAwsRoute53QueryLogs) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *aws_v1.AwsRoute53QueryLog, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(awsroute53querylogsResource, c.ns, name, data, subresources...), &aws_v1.AwsRoute53QueryLog{})

	if obj == nil {
		return nil, err
	}
	return obj.(*aws_v1.AwsRoute53QueryLog), err
}
