/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	aws_v1 "github.com/trussle/terraform-operator/pkg/apis/aws/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeAwsDefaultRouteTables implements AwsDefaultRouteTableInterface
type FakeAwsDefaultRouteTables struct {
	Fake *FakeTrussleV1
	ns   string
}

var awsdefaultroutetablesResource = schema.GroupVersionResource{Group: "trussle.com", Version: "v1", Resource: "awsdefaultroutetables"}

var awsdefaultroutetablesKind = schema.GroupVersionKind{Group: "trussle.com", Version: "v1", Kind: "AwsDefaultRouteTable"}

// Get takes name of the awsDefaultRouteTable, and returns the corresponding awsDefaultRouteTable object, and an error if there is any.
func (c *FakeAwsDefaultRouteTables) Get(name string, options v1.GetOptions) (result *aws_v1.AwsDefaultRouteTable, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(awsdefaultroutetablesResource, c.ns, name), &aws_v1.AwsDefaultRouteTable{})

	if obj == nil {
		return nil, err
	}
	return obj.(*aws_v1.AwsDefaultRouteTable), err
}

// List takes label and field selectors, and returns the list of AwsDefaultRouteTables that match those selectors.
func (c *FakeAwsDefaultRouteTables) List(opts v1.ListOptions) (result *aws_v1.AwsDefaultRouteTableList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(awsdefaultroutetablesResource, awsdefaultroutetablesKind, c.ns, opts), &aws_v1.AwsDefaultRouteTableList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &aws_v1.AwsDefaultRouteTableList{}
	for _, item := range obj.(*aws_v1.AwsDefaultRouteTableList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested awsDefaultRouteTables.
func (c *FakeAwsDefaultRouteTables) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(awsdefaultroutetablesResource, c.ns, opts))

}

// Create takes the representation of a awsDefaultRouteTable and creates it.  Returns the server's representation of the awsDefaultRouteTable, and an error, if there is any.
func (c *FakeAwsDefaultRouteTables) Create(awsDefaultRouteTable *aws_v1.AwsDefaultRouteTable) (result *aws_v1.AwsDefaultRouteTable, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(awsdefaultroutetablesResource, c.ns, awsDefaultRouteTable), &aws_v1.AwsDefaultRouteTable{})

	if obj == nil {
		return nil, err
	}
	return obj.(*aws_v1.AwsDefaultRouteTable), err
}

// Update takes the representation of a awsDefaultRouteTable and updates it. Returns the server's representation of the awsDefaultRouteTable, and an error, if there is any.
func (c *FakeAwsDefaultRouteTables) Update(awsDefaultRouteTable *aws_v1.AwsDefaultRouteTable) (result *aws_v1.AwsDefaultRouteTable, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(awsdefaultroutetablesResource, c.ns, awsDefaultRouteTable), &aws_v1.AwsDefaultRouteTable{})

	if obj == nil {
		return nil, err
	}
	return obj.(*aws_v1.AwsDefaultRouteTable), err
}

// Delete takes name of the awsDefaultRouteTable and deletes it. Returns an error if one occurs.
func (c *FakeAwsDefaultRouteTables) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(awsdefaultroutetablesResource, c.ns, name), &aws_v1.AwsDefaultRouteTable{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeAwsDefaultRouteTables) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(awsdefaultroutetablesResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &aws_v1.AwsDefaultRouteTableList{})
	return err
}

// Patch applies the patch and returns the patched awsDefaultRouteTable.
func (c *FakeAwsDefaultRouteTables) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *aws_v1.AwsDefaultRouteTable, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(awsdefaultroutetablesResource, c.ns, name, data, subresources...), &aws_v1.AwsDefaultRouteTable{})

	if obj == nil {
		return nil, err
	}
	return obj.(*aws_v1.AwsDefaultRouteTable), err
}
