/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	aws_v1 "github.com/trussle/terraform-operator/pkg/apis/aws/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeAwsAppCookieStickinessPolicies implements AwsAppCookieStickinessPolicyInterface
type FakeAwsAppCookieStickinessPolicies struct {
	Fake *FakeTrussleV1
	ns   string
}

var awsappcookiestickinesspoliciesResource = schema.GroupVersionResource{Group: "trussle.com", Version: "v1", Resource: "awsappcookiestickinesspolicies"}

var awsappcookiestickinesspoliciesKind = schema.GroupVersionKind{Group: "trussle.com", Version: "v1", Kind: "AwsAppCookieStickinessPolicy"}

// Get takes name of the awsAppCookieStickinessPolicy, and returns the corresponding awsAppCookieStickinessPolicy object, and an error if there is any.
func (c *FakeAwsAppCookieStickinessPolicies) Get(name string, options v1.GetOptions) (result *aws_v1.AwsAppCookieStickinessPolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(awsappcookiestickinesspoliciesResource, c.ns, name), &aws_v1.AwsAppCookieStickinessPolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*aws_v1.AwsAppCookieStickinessPolicy), err
}

// List takes label and field selectors, and returns the list of AwsAppCookieStickinessPolicies that match those selectors.
func (c *FakeAwsAppCookieStickinessPolicies) List(opts v1.ListOptions) (result *aws_v1.AwsAppCookieStickinessPolicyList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(awsappcookiestickinesspoliciesResource, awsappcookiestickinesspoliciesKind, c.ns, opts), &aws_v1.AwsAppCookieStickinessPolicyList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &aws_v1.AwsAppCookieStickinessPolicyList{}
	for _, item := range obj.(*aws_v1.AwsAppCookieStickinessPolicyList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested awsAppCookieStickinessPolicies.
func (c *FakeAwsAppCookieStickinessPolicies) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(awsappcookiestickinesspoliciesResource, c.ns, opts))

}

// Create takes the representation of a awsAppCookieStickinessPolicy and creates it.  Returns the server's representation of the awsAppCookieStickinessPolicy, and an error, if there is any.
func (c *FakeAwsAppCookieStickinessPolicies) Create(awsAppCookieStickinessPolicy *aws_v1.AwsAppCookieStickinessPolicy) (result *aws_v1.AwsAppCookieStickinessPolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(awsappcookiestickinesspoliciesResource, c.ns, awsAppCookieStickinessPolicy), &aws_v1.AwsAppCookieStickinessPolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*aws_v1.AwsAppCookieStickinessPolicy), err
}

// Update takes the representation of a awsAppCookieStickinessPolicy and updates it. Returns the server's representation of the awsAppCookieStickinessPolicy, and an error, if there is any.
func (c *FakeAwsAppCookieStickinessPolicies) Update(awsAppCookieStickinessPolicy *aws_v1.AwsAppCookieStickinessPolicy) (result *aws_v1.AwsAppCookieStickinessPolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(awsappcookiestickinesspoliciesResource, c.ns, awsAppCookieStickinessPolicy), &aws_v1.AwsAppCookieStickinessPolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*aws_v1.AwsAppCookieStickinessPolicy), err
}

// Delete takes name of the awsAppCookieStickinessPolicy and deletes it. Returns an error if one occurs.
func (c *FakeAwsAppCookieStickinessPolicies) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(awsappcookiestickinesspoliciesResource, c.ns, name), &aws_v1.AwsAppCookieStickinessPolicy{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeAwsAppCookieStickinessPolicies) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(awsappcookiestickinesspoliciesResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &aws_v1.AwsAppCookieStickinessPolicyList{})
	return err
}

// Patch applies the patch and returns the patched awsAppCookieStickinessPolicy.
func (c *FakeAwsAppCookieStickinessPolicies) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *aws_v1.AwsAppCookieStickinessPolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(awsappcookiestickinesspoliciesResource, c.ns, name, data, subresources...), &aws_v1.AwsAppCookieStickinessPolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*aws_v1.AwsAppCookieStickinessPolicy), err
}
