/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	aws_v1 "github.com/trussle/terraform-operator/pkg/apis/aws/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeAwsEips implements AwsEipInterface
type FakeAwsEips struct {
	Fake *FakeTrussleV1
	ns   string
}

var awseipsResource = schema.GroupVersionResource{Group: "trussle.com", Version: "v1", Resource: "awseips"}

var awseipsKind = schema.GroupVersionKind{Group: "trussle.com", Version: "v1", Kind: "AwsEip"}

// Get takes name of the awsEip, and returns the corresponding awsEip object, and an error if there is any.
func (c *FakeAwsEips) Get(name string, options v1.GetOptions) (result *aws_v1.AwsEip, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(awseipsResource, c.ns, name), &aws_v1.AwsEip{})

	if obj == nil {
		return nil, err
	}
	return obj.(*aws_v1.AwsEip), err
}

// List takes label and field selectors, and returns the list of AwsEips that match those selectors.
func (c *FakeAwsEips) List(opts v1.ListOptions) (result *aws_v1.AwsEipList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(awseipsResource, awseipsKind, c.ns, opts), &aws_v1.AwsEipList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &aws_v1.AwsEipList{}
	for _, item := range obj.(*aws_v1.AwsEipList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested awsEips.
func (c *FakeAwsEips) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(awseipsResource, c.ns, opts))

}

// Create takes the representation of a awsEip and creates it.  Returns the server's representation of the awsEip, and an error, if there is any.
func (c *FakeAwsEips) Create(awsEip *aws_v1.AwsEip) (result *aws_v1.AwsEip, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(awseipsResource, c.ns, awsEip), &aws_v1.AwsEip{})

	if obj == nil {
		return nil, err
	}
	return obj.(*aws_v1.AwsEip), err
}

// Update takes the representation of a awsEip and updates it. Returns the server's representation of the awsEip, and an error, if there is any.
func (c *FakeAwsEips) Update(awsEip *aws_v1.AwsEip) (result *aws_v1.AwsEip, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(awseipsResource, c.ns, awsEip), &aws_v1.AwsEip{})

	if obj == nil {
		return nil, err
	}
	return obj.(*aws_v1.AwsEip), err
}

// Delete takes name of the awsEip and deletes it. Returns an error if one occurs.
func (c *FakeAwsEips) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(awseipsResource, c.ns, name), &aws_v1.AwsEip{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeAwsEips) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(awseipsResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &aws_v1.AwsEipList{})
	return err
}

// Patch applies the patch and returns the patched awsEip.
func (c *FakeAwsEips) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *aws_v1.AwsEip, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(awseipsResource, c.ns, name, data, subresources...), &aws_v1.AwsEip{})

	if obj == nil {
		return nil, err
	}
	return obj.(*aws_v1.AwsEip), err
}
