/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	aws_v1 "github.com/trussle/terraform-operator/pkg/apis/aws/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeAwsElasticacheReplicationGroups implements AwsElasticacheReplicationGroupInterface
type FakeAwsElasticacheReplicationGroups struct {
	Fake *FakeTrussleV1
	ns   string
}

var awselasticachereplicationgroupsResource = schema.GroupVersionResource{Group: "trussle.com", Version: "v1", Resource: "awselasticachereplicationgroups"}

var awselasticachereplicationgroupsKind = schema.GroupVersionKind{Group: "trussle.com", Version: "v1", Kind: "AwsElasticacheReplicationGroup"}

// Get takes name of the awsElasticacheReplicationGroup, and returns the corresponding awsElasticacheReplicationGroup object, and an error if there is any.
func (c *FakeAwsElasticacheReplicationGroups) Get(name string, options v1.GetOptions) (result *aws_v1.AwsElasticacheReplicationGroup, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(awselasticachereplicationgroupsResource, c.ns, name), &aws_v1.AwsElasticacheReplicationGroup{})

	if obj == nil {
		return nil, err
	}
	return obj.(*aws_v1.AwsElasticacheReplicationGroup), err
}

// List takes label and field selectors, and returns the list of AwsElasticacheReplicationGroups that match those selectors.
func (c *FakeAwsElasticacheReplicationGroups) List(opts v1.ListOptions) (result *aws_v1.AwsElasticacheReplicationGroupList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(awselasticachereplicationgroupsResource, awselasticachereplicationgroupsKind, c.ns, opts), &aws_v1.AwsElasticacheReplicationGroupList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &aws_v1.AwsElasticacheReplicationGroupList{}
	for _, item := range obj.(*aws_v1.AwsElasticacheReplicationGroupList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested awsElasticacheReplicationGroups.
func (c *FakeAwsElasticacheReplicationGroups) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(awselasticachereplicationgroupsResource, c.ns, opts))

}

// Create takes the representation of a awsElasticacheReplicationGroup and creates it.  Returns the server's representation of the awsElasticacheReplicationGroup, and an error, if there is any.
func (c *FakeAwsElasticacheReplicationGroups) Create(awsElasticacheReplicationGroup *aws_v1.AwsElasticacheReplicationGroup) (result *aws_v1.AwsElasticacheReplicationGroup, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(awselasticachereplicationgroupsResource, c.ns, awsElasticacheReplicationGroup), &aws_v1.AwsElasticacheReplicationGroup{})

	if obj == nil {
		return nil, err
	}
	return obj.(*aws_v1.AwsElasticacheReplicationGroup), err
}

// Update takes the representation of a awsElasticacheReplicationGroup and updates it. Returns the server's representation of the awsElasticacheReplicationGroup, and an error, if there is any.
func (c *FakeAwsElasticacheReplicationGroups) Update(awsElasticacheReplicationGroup *aws_v1.AwsElasticacheReplicationGroup) (result *aws_v1.AwsElasticacheReplicationGroup, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(awselasticachereplicationgroupsResource, c.ns, awsElasticacheReplicationGroup), &aws_v1.AwsElasticacheReplicationGroup{})

	if obj == nil {
		return nil, err
	}
	return obj.(*aws_v1.AwsElasticacheReplicationGroup), err
}

// Delete takes name of the awsElasticacheReplicationGroup and deletes it. Returns an error if one occurs.
func (c *FakeAwsElasticacheReplicationGroups) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(awselasticachereplicationgroupsResource, c.ns, name), &aws_v1.AwsElasticacheReplicationGroup{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeAwsElasticacheReplicationGroups) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(awselasticachereplicationgroupsResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &aws_v1.AwsElasticacheReplicationGroupList{})
	return err
}

// Patch applies the patch and returns the patched awsElasticacheReplicationGroup.
func (c *FakeAwsElasticacheReplicationGroups) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *aws_v1.AwsElasticacheReplicationGroup, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(awselasticachereplicationgroupsResource, c.ns, name, data, subresources...), &aws_v1.AwsElasticacheReplicationGroup{})

	if obj == nil {
		return nil, err
	}
	return obj.(*aws_v1.AwsElasticacheReplicationGroup), err
}
