/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	aws_v1 "github.com/trussle/terraform-operator/pkg/apis/aws/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeAwsAutoscalingAttachments implements AwsAutoscalingAttachmentInterface
type FakeAwsAutoscalingAttachments struct {
	Fake *FakeTrussleV1
	ns   string
}

var awsautoscalingattachmentsResource = schema.GroupVersionResource{Group: "trussle.com", Version: "v1", Resource: "awsautoscalingattachments"}

var awsautoscalingattachmentsKind = schema.GroupVersionKind{Group: "trussle.com", Version: "v1", Kind: "AwsAutoscalingAttachment"}

// Get takes name of the awsAutoscalingAttachment, and returns the corresponding awsAutoscalingAttachment object, and an error if there is any.
func (c *FakeAwsAutoscalingAttachments) Get(name string, options v1.GetOptions) (result *aws_v1.AwsAutoscalingAttachment, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(awsautoscalingattachmentsResource, c.ns, name), &aws_v1.AwsAutoscalingAttachment{})

	if obj == nil {
		return nil, err
	}
	return obj.(*aws_v1.AwsAutoscalingAttachment), err
}

// List takes label and field selectors, and returns the list of AwsAutoscalingAttachments that match those selectors.
func (c *FakeAwsAutoscalingAttachments) List(opts v1.ListOptions) (result *aws_v1.AwsAutoscalingAttachmentList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(awsautoscalingattachmentsResource, awsautoscalingattachmentsKind, c.ns, opts), &aws_v1.AwsAutoscalingAttachmentList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &aws_v1.AwsAutoscalingAttachmentList{}
	for _, item := range obj.(*aws_v1.AwsAutoscalingAttachmentList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested awsAutoscalingAttachments.
func (c *FakeAwsAutoscalingAttachments) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(awsautoscalingattachmentsResource, c.ns, opts))

}

// Create takes the representation of a awsAutoscalingAttachment and creates it.  Returns the server's representation of the awsAutoscalingAttachment, and an error, if there is any.
func (c *FakeAwsAutoscalingAttachments) Create(awsAutoscalingAttachment *aws_v1.AwsAutoscalingAttachment) (result *aws_v1.AwsAutoscalingAttachment, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(awsautoscalingattachmentsResource, c.ns, awsAutoscalingAttachment), &aws_v1.AwsAutoscalingAttachment{})

	if obj == nil {
		return nil, err
	}
	return obj.(*aws_v1.AwsAutoscalingAttachment), err
}

// Update takes the representation of a awsAutoscalingAttachment and updates it. Returns the server's representation of the awsAutoscalingAttachment, and an error, if there is any.
func (c *FakeAwsAutoscalingAttachments) Update(awsAutoscalingAttachment *aws_v1.AwsAutoscalingAttachment) (result *aws_v1.AwsAutoscalingAttachment, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(awsautoscalingattachmentsResource, c.ns, awsAutoscalingAttachment), &aws_v1.AwsAutoscalingAttachment{})

	if obj == nil {
		return nil, err
	}
	return obj.(*aws_v1.AwsAutoscalingAttachment), err
}

// Delete takes name of the awsAutoscalingAttachment and deletes it. Returns an error if one occurs.
func (c *FakeAwsAutoscalingAttachments) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(awsautoscalingattachmentsResource, c.ns, name), &aws_v1.AwsAutoscalingAttachment{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeAwsAutoscalingAttachments) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(awsautoscalingattachmentsResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &aws_v1.AwsAutoscalingAttachmentList{})
	return err
}

// Patch applies the patch and returns the patched awsAutoscalingAttachment.
func (c *FakeAwsAutoscalingAttachments) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *aws_v1.AwsAutoscalingAttachment, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(awsautoscalingattachmentsResource, c.ns, name, data, subresources...), &aws_v1.AwsAutoscalingAttachment{})

	if obj == nil {
		return nil, err
	}
	return obj.(*aws_v1.AwsAutoscalingAttachment), err
}
