/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	aws_v1 "github.com/trussle/terraform-operator/pkg/apis/aws/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeAwsCognitoUserPoolClients implements AwsCognitoUserPoolClientInterface
type FakeAwsCognitoUserPoolClients struct {
	Fake *FakeTrussleV1
	ns   string
}

var awscognitouserpoolclientsResource = schema.GroupVersionResource{Group: "trussle.com", Version: "v1", Resource: "awscognitouserpoolclients"}

var awscognitouserpoolclientsKind = schema.GroupVersionKind{Group: "trussle.com", Version: "v1", Kind: "AwsCognitoUserPoolClient"}

// Get takes name of the awsCognitoUserPoolClient, and returns the corresponding awsCognitoUserPoolClient object, and an error if there is any.
func (c *FakeAwsCognitoUserPoolClients) Get(name string, options v1.GetOptions) (result *aws_v1.AwsCognitoUserPoolClient, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(awscognitouserpoolclientsResource, c.ns, name), &aws_v1.AwsCognitoUserPoolClient{})

	if obj == nil {
		return nil, err
	}
	return obj.(*aws_v1.AwsCognitoUserPoolClient), err
}

// List takes label and field selectors, and returns the list of AwsCognitoUserPoolClients that match those selectors.
func (c *FakeAwsCognitoUserPoolClients) List(opts v1.ListOptions) (result *aws_v1.AwsCognitoUserPoolClientList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(awscognitouserpoolclientsResource, awscognitouserpoolclientsKind, c.ns, opts), &aws_v1.AwsCognitoUserPoolClientList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &aws_v1.AwsCognitoUserPoolClientList{}
	for _, item := range obj.(*aws_v1.AwsCognitoUserPoolClientList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested awsCognitoUserPoolClients.
func (c *FakeAwsCognitoUserPoolClients) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(awscognitouserpoolclientsResource, c.ns, opts))

}

// Create takes the representation of a awsCognitoUserPoolClient and creates it.  Returns the server's representation of the awsCognitoUserPoolClient, and an error, if there is any.
func (c *FakeAwsCognitoUserPoolClients) Create(awsCognitoUserPoolClient *aws_v1.AwsCognitoUserPoolClient) (result *aws_v1.AwsCognitoUserPoolClient, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(awscognitouserpoolclientsResource, c.ns, awsCognitoUserPoolClient), &aws_v1.AwsCognitoUserPoolClient{})

	if obj == nil {
		return nil, err
	}
	return obj.(*aws_v1.AwsCognitoUserPoolClient), err
}

// Update takes the representation of a awsCognitoUserPoolClient and updates it. Returns the server's representation of the awsCognitoUserPoolClient, and an error, if there is any.
func (c *FakeAwsCognitoUserPoolClients) Update(awsCognitoUserPoolClient *aws_v1.AwsCognitoUserPoolClient) (result *aws_v1.AwsCognitoUserPoolClient, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(awscognitouserpoolclientsResource, c.ns, awsCognitoUserPoolClient), &aws_v1.AwsCognitoUserPoolClient{})

	if obj == nil {
		return nil, err
	}
	return obj.(*aws_v1.AwsCognitoUserPoolClient), err
}

// Delete takes name of the awsCognitoUserPoolClient and deletes it. Returns an error if one occurs.
func (c *FakeAwsCognitoUserPoolClients) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(awscognitouserpoolclientsResource, c.ns, name), &aws_v1.AwsCognitoUserPoolClient{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeAwsCognitoUserPoolClients) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(awscognitouserpoolclientsResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &aws_v1.AwsCognitoUserPoolClientList{})
	return err
}

// Patch applies the patch and returns the patched awsCognitoUserPoolClient.
func (c *FakeAwsCognitoUserPoolClients) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *aws_v1.AwsCognitoUserPoolClient, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(awscognitouserpoolclientsResource, c.ns, name, data, subresources...), &aws_v1.AwsCognitoUserPoolClient{})

	if obj == nil {
		return nil, err
	}
	return obj.(*aws_v1.AwsCognitoUserPoolClient), err
}
