/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	aws_v1 "github.com/trussle/terraform-operator/pkg/apis/aws/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeAwsWafregionalRuleGroups implements AwsWafregionalRuleGroupInterface
type FakeAwsWafregionalRuleGroups struct {
	Fake *FakeTrussleV1
	ns   string
}

var awswafregionalrulegroupsResource = schema.GroupVersionResource{Group: "trussle.com", Version: "v1", Resource: "awswafregionalrulegroups"}

var awswafregionalrulegroupsKind = schema.GroupVersionKind{Group: "trussle.com", Version: "v1", Kind: "AwsWafregionalRuleGroup"}

// Get takes name of the awsWafregionalRuleGroup, and returns the corresponding awsWafregionalRuleGroup object, and an error if there is any.
func (c *FakeAwsWafregionalRuleGroups) Get(name string, options v1.GetOptions) (result *aws_v1.AwsWafregionalRuleGroup, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(awswafregionalrulegroupsResource, c.ns, name), &aws_v1.AwsWafregionalRuleGroup{})

	if obj == nil {
		return nil, err
	}
	return obj.(*aws_v1.AwsWafregionalRuleGroup), err
}

// List takes label and field selectors, and returns the list of AwsWafregionalRuleGroups that match those selectors.
func (c *FakeAwsWafregionalRuleGroups) List(opts v1.ListOptions) (result *aws_v1.AwsWafregionalRuleGroupList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(awswafregionalrulegroupsResource, awswafregionalrulegroupsKind, c.ns, opts), &aws_v1.AwsWafregionalRuleGroupList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &aws_v1.AwsWafregionalRuleGroupList{}
	for _, item := range obj.(*aws_v1.AwsWafregionalRuleGroupList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested awsWafregionalRuleGroups.
func (c *FakeAwsWafregionalRuleGroups) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(awswafregionalrulegroupsResource, c.ns, opts))

}

// Create takes the representation of a awsWafregionalRuleGroup and creates it.  Returns the server's representation of the awsWafregionalRuleGroup, and an error, if there is any.
func (c *FakeAwsWafregionalRuleGroups) Create(awsWafregionalRuleGroup *aws_v1.AwsWafregionalRuleGroup) (result *aws_v1.AwsWafregionalRuleGroup, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(awswafregionalrulegroupsResource, c.ns, awsWafregionalRuleGroup), &aws_v1.AwsWafregionalRuleGroup{})

	if obj == nil {
		return nil, err
	}
	return obj.(*aws_v1.AwsWafregionalRuleGroup), err
}

// Update takes the representation of a awsWafregionalRuleGroup and updates it. Returns the server's representation of the awsWafregionalRuleGroup, and an error, if there is any.
func (c *FakeAwsWafregionalRuleGroups) Update(awsWafregionalRuleGroup *aws_v1.AwsWafregionalRuleGroup) (result *aws_v1.AwsWafregionalRuleGroup, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(awswafregionalrulegroupsResource, c.ns, awsWafregionalRuleGroup), &aws_v1.AwsWafregionalRuleGroup{})

	if obj == nil {
		return nil, err
	}
	return obj.(*aws_v1.AwsWafregionalRuleGroup), err
}

// Delete takes name of the awsWafregionalRuleGroup and deletes it. Returns an error if one occurs.
func (c *FakeAwsWafregionalRuleGroups) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(awswafregionalrulegroupsResource, c.ns, name), &aws_v1.AwsWafregionalRuleGroup{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeAwsWafregionalRuleGroups) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(awswafregionalrulegroupsResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &aws_v1.AwsWafregionalRuleGroupList{})
	return err
}

// Patch applies the patch and returns the patched awsWafregionalRuleGroup.
func (c *FakeAwsWafregionalRuleGroups) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *aws_v1.AwsWafregionalRuleGroup, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(awswafregionalrulegroupsResource, c.ns, name, data, subresources...), &aws_v1.AwsWafregionalRuleGroup{})

	if obj == nil {
		return nil, err
	}
	return obj.(*aws_v1.AwsWafregionalRuleGroup), err
}
