/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	aws_v1 "github.com/trussle/terraform-operator/pkg/apis/aws/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeAwsGlueConnections implements AwsGlueConnectionInterface
type FakeAwsGlueConnections struct {
	Fake *FakeTrussleV1
	ns   string
}

var awsglueconnectionsResource = schema.GroupVersionResource{Group: "trussle.com", Version: "v1", Resource: "awsglueconnections"}

var awsglueconnectionsKind = schema.GroupVersionKind{Group: "trussle.com", Version: "v1", Kind: "AwsGlueConnection"}

// Get takes name of the awsGlueConnection, and returns the corresponding awsGlueConnection object, and an error if there is any.
func (c *FakeAwsGlueConnections) Get(name string, options v1.GetOptions) (result *aws_v1.AwsGlueConnection, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(awsglueconnectionsResource, c.ns, name), &aws_v1.AwsGlueConnection{})

	if obj == nil {
		return nil, err
	}
	return obj.(*aws_v1.AwsGlueConnection), err
}

// List takes label and field selectors, and returns the list of AwsGlueConnections that match those selectors.
func (c *FakeAwsGlueConnections) List(opts v1.ListOptions) (result *aws_v1.AwsGlueConnectionList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(awsglueconnectionsResource, awsglueconnectionsKind, c.ns, opts), &aws_v1.AwsGlueConnectionList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &aws_v1.AwsGlueConnectionList{}
	for _, item := range obj.(*aws_v1.AwsGlueConnectionList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested awsGlueConnections.
func (c *FakeAwsGlueConnections) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(awsglueconnectionsResource, c.ns, opts))

}

// Create takes the representation of a awsGlueConnection and creates it.  Returns the server's representation of the awsGlueConnection, and an error, if there is any.
func (c *FakeAwsGlueConnections) Create(awsGlueConnection *aws_v1.AwsGlueConnection) (result *aws_v1.AwsGlueConnection, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(awsglueconnectionsResource, c.ns, awsGlueConnection), &aws_v1.AwsGlueConnection{})

	if obj == nil {
		return nil, err
	}
	return obj.(*aws_v1.AwsGlueConnection), err
}

// Update takes the representation of a awsGlueConnection and updates it. Returns the server's representation of the awsGlueConnection, and an error, if there is any.
func (c *FakeAwsGlueConnections) Update(awsGlueConnection *aws_v1.AwsGlueConnection) (result *aws_v1.AwsGlueConnection, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(awsglueconnectionsResource, c.ns, awsGlueConnection), &aws_v1.AwsGlueConnection{})

	if obj == nil {
		return nil, err
	}
	return obj.(*aws_v1.AwsGlueConnection), err
}

// Delete takes name of the awsGlueConnection and deletes it. Returns an error if one occurs.
func (c *FakeAwsGlueConnections) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(awsglueconnectionsResource, c.ns, name), &aws_v1.AwsGlueConnection{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeAwsGlueConnections) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(awsglueconnectionsResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &aws_v1.AwsGlueConnectionList{})
	return err
}

// Patch applies the patch and returns the patched awsGlueConnection.
func (c *FakeAwsGlueConnections) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *aws_v1.AwsGlueConnection, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(awsglueconnectionsResource, c.ns, name, data, subresources...), &aws_v1.AwsGlueConnection{})

	if obj == nil {
		return nil, err
	}
	return obj.(*aws_v1.AwsGlueConnection), err
}
