/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	aws_v1 "github.com/trussle/terraform-operator/pkg/apis/aws/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeAwsCloudtrails implements AwsCloudtrailInterface
type FakeAwsCloudtrails struct {
	Fake *FakeTrussleV1
	ns   string
}

var awscloudtrailsResource = schema.GroupVersionResource{Group: "trussle.com", Version: "v1", Resource: "awscloudtrails"}

var awscloudtrailsKind = schema.GroupVersionKind{Group: "trussle.com", Version: "v1", Kind: "AwsCloudtrail"}

// Get takes name of the awsCloudtrail, and returns the corresponding awsCloudtrail object, and an error if there is any.
func (c *FakeAwsCloudtrails) Get(name string, options v1.GetOptions) (result *aws_v1.AwsCloudtrail, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(awscloudtrailsResource, c.ns, name), &aws_v1.AwsCloudtrail{})

	if obj == nil {
		return nil, err
	}
	return obj.(*aws_v1.AwsCloudtrail), err
}

// List takes label and field selectors, and returns the list of AwsCloudtrails that match those selectors.
func (c *FakeAwsCloudtrails) List(opts v1.ListOptions) (result *aws_v1.AwsCloudtrailList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(awscloudtrailsResource, awscloudtrailsKind, c.ns, opts), &aws_v1.AwsCloudtrailList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &aws_v1.AwsCloudtrailList{}
	for _, item := range obj.(*aws_v1.AwsCloudtrailList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested awsCloudtrails.
func (c *FakeAwsCloudtrails) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(awscloudtrailsResource, c.ns, opts))

}

// Create takes the representation of a awsCloudtrail and creates it.  Returns the server's representation of the awsCloudtrail, and an error, if there is any.
func (c *FakeAwsCloudtrails) Create(awsCloudtrail *aws_v1.AwsCloudtrail) (result *aws_v1.AwsCloudtrail, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(awscloudtrailsResource, c.ns, awsCloudtrail), &aws_v1.AwsCloudtrail{})

	if obj == nil {
		return nil, err
	}
	return obj.(*aws_v1.AwsCloudtrail), err
}

// Update takes the representation of a awsCloudtrail and updates it. Returns the server's representation of the awsCloudtrail, and an error, if there is any.
func (c *FakeAwsCloudtrails) Update(awsCloudtrail *aws_v1.AwsCloudtrail) (result *aws_v1.AwsCloudtrail, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(awscloudtrailsResource, c.ns, awsCloudtrail), &aws_v1.AwsCloudtrail{})

	if obj == nil {
		return nil, err
	}
	return obj.(*aws_v1.AwsCloudtrail), err
}

// Delete takes name of the awsCloudtrail and deletes it. Returns an error if one occurs.
func (c *FakeAwsCloudtrails) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(awscloudtrailsResource, c.ns, name), &aws_v1.AwsCloudtrail{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeAwsCloudtrails) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(awscloudtrailsResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &aws_v1.AwsCloudtrailList{})
	return err
}

// Patch applies the patch and returns the patched awsCloudtrail.
func (c *FakeAwsCloudtrails) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *aws_v1.AwsCloudtrail, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(awscloudtrailsResource, c.ns, name, data, subresources...), &aws_v1.AwsCloudtrail{})

	if obj == nil {
		return nil, err
	}
	return obj.(*aws_v1.AwsCloudtrail), err
}
