
	package v1

	import (
		meta_v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
		"k8s.io/apimachinery/pkg/runtime"
		"k8s.io/apimachinery/pkg/runtime/schema"
	
		"github.com/trussle/terraform-controller/pkg/apis/aws"
	)
	
	// GroupVersion is the identifier for the API which includes
	// the name of the group and the version of the API
	var SchemeGroupVersion = schema.GroupVersion{
		Group:   aws.GroupName,
		Version: "v1",
	}
	
	// create a SchemeBuilder which uses functions to add types to
	// the scheme
	var AddToScheme = runtime.NewSchemeBuilder(addKnownTypes).AddToScheme
	
	func Resource(resource string) schema.GroupResource {
		return SchemeGroupVersion.WithResource(resource).GroupResource()
	}
	func addKnownTypes(scheme *runtime.Scheme) error {
		schema.AddKnownTypes(
			SchemeGroupVersion,
			&AwsInspectorAssessmentTemplate{}
			&AwsInspectorAssessmentTemplateList{}
			&AwsSesDomainIdentity{}
			&AwsSesDomainIdentityList{}
			&AwsSesEventDestination{}
			&AwsSesEventDestinationList{}
			&AwsSsmResourceDataSync{}
			&AwsSsmResourceDataSyncList{}
			&AwsAlbTargetGroup{}
			&AwsAlbTargetGroupList{}
			&AwsCognitoUserGroup{}
			&AwsCognitoUserGroupList{}
			&AwsEbsSnapshot{}
			&AwsEbsSnapshotList{}
			&AwsAthenaNamedQuery{}
			&AwsAthenaNamedQueryList{}
			&AwsGuarddutyThreatintelset{}
			&AwsGuarddutyThreatintelsetList{}
			&AwsIotThingType{}
			&AwsIotThingTypeList{}
			&AwsServiceDiscoveryPrivateDnsNamespace{}
			&AwsServiceDiscoveryPrivateDnsNamespaceList{}
			&AwsVpc{}
			&AwsVpcList{}
			&AwsWafByteMatchSet{}
			&AwsWafByteMatchSetList{}
			&AwsApiGatewayDocumentationVersion{}
			&AwsApiGatewayDocumentationVersionList{}
			&AwsApiGatewayGatewayResponse{}
			&AwsApiGatewayGatewayResponseList{}
			&AwsWafRegexPatternSet{}
			&AwsWafRegexPatternSetList{}
			&AwsOpsworksCustomLayer{}
			&AwsOpsworksCustomLayerList{}
			&AwsRedshiftParameterGroup{}
			&AwsRedshiftParameterGroupList{}
			&AwsSimpledbDomain{}
			&AwsSimpledbDomainList{}
			&AwsAlbListenerRule{}
			&AwsAlbListenerRuleList{}
			&AwsApiGatewayIntegrationResponse{}
			&AwsApiGatewayIntegrationResponseList{}
			&AwsIamPolicy{}
			&AwsIamPolicyList{}
			&AwsFlowLog{}
			&AwsFlowLogList{}
			&AwsRoute53Record{}
			&AwsRoute53RecordList{}
			&AwsDefaultSubnet{}
			&AwsDefaultSubnetList{}
			&AwsWafregionalWebAclAssociation{}
			&AwsWafregionalWebAclAssociationList{}
			&AwsAppsyncGraphqlApi{}
			&AwsAppsyncGraphqlApiList{}
			&AwsCodedeployDeploymentGroup{}
			&AwsCodedeployDeploymentGroupList{}
			&AwsGuarddutyDetector{}
			&AwsGuarddutyDetectorList{}
			&AwsIotTopicRule{}
			&AwsIotTopicRuleList{}
			&AwsLoadBalancerListenerPolicy{}
			&AwsLoadBalancerListenerPolicyList{}
			&AwsNetworkAclRule{}
			&AwsNetworkAclRuleList{}
			&AwsS3Bucket{}
			&AwsS3BucketList{}
			&AwsDefaultSecurityGroup{}
			&AwsDefaultSecurityGroupList{}
			&AwsDbOptionGroup{}
			&AwsDbOptionGroupList{}
			&AwsElbAttachment{}
			&AwsElbAttachmentList{}
			&AwsDmsReplicationTask{}
			&AwsDmsReplicationTaskList{}
			&AwsElasticacheReplicationGroup{}
			&AwsElasticacheReplicationGroupList{}
			&AwsAmi{}
			&AwsAmiList{}
			&AwsDmsReplicationSubnetGroup{}
			&AwsDmsReplicationSubnetGroupList{}
			&AwsDxConnection{}
			&AwsDxConnectionList{}
			&AwsAppsyncDatasource{}
			&AwsAppsyncDatasourceList{}
			&AwsCodepipeline{}
			&AwsCodepipelineList{}
			&AwsAppautoscalingTarget{}
			&AwsAppautoscalingTargetList{}
			&AwsCloudformationStack{}
			&AwsCloudformationStackList{}
			&AwsCognitoIdentityPool{}
			&AwsCognitoIdentityPoolList{}
			&AwsAcmCertificate{}
			&AwsAcmCertificateList{}
			&AwsAmiLaunchPermission{}
			&AwsAmiLaunchPermissionList{}
			&AwsWafRuleGroup{}
			&AwsWafRuleGroupList{}
			&AwsWafregionalWebAcl{}
			&AwsWafregionalWebAclList{}
			&AwsApiGatewayRequestValidator{}
			&AwsApiGatewayRequestValidatorList{}
			&AwsKeyPair{}
			&AwsKeyPairList{}
			&AwsIotPolicy{}
			&AwsIotPolicyList{}
			&AwsLightsailKeyPair{}
			&AwsLightsailKeyPairList{}
			&AwsRedshiftCluster{}
			&AwsRedshiftClusterList{}
			&AwsSpotFleetRequest{}
			&AwsSpotFleetRequestList{}
			&AwsWafregionalSqlInjectionMatchSet{}
			&AwsWafregionalSqlInjectionMatchSetList{}
			&AwsAppCookieStickinessPolicy{}
			&AwsAppCookieStickinessPolicyList{}
			&AwsInstance{}
			&AwsInstanceList{}
			&AwsElasticacheParameterGroup{}
			&AwsElasticacheParameterGroupList{}
			&AwsGuarddutyMember{}
			&AwsGuarddutyMemberList{}
			&AwsVpcPeeringConnectionAccepter{}
			&AwsVpcPeeringConnectionAccepterList{}
			&AwsVpnGatewayAttachment{}
			&AwsVpnGatewayAttachmentList{}
			&AwsCognitoUserPoolDomain{}
			&AwsCognitoUserPoolDomainList{}
			&AwsEcsService{}
			&AwsEcsServiceList{}
			&AwsRouteTableAssociation{}
			&AwsRouteTableAssociationList{}
			&AwsWafRegexMatchSet{}
			&AwsWafRegexMatchSetList{}
			&AwsWafregionalByteMatchSet{}
			&AwsWafregionalByteMatchSetList{}
			&AwsEmrInstanceGroup{}
			&AwsEmrInstanceGroupList{}
			&AwsEmrSecurityConfiguration{}
			&AwsEmrSecurityConfigurationList{}
			&AwsElb{}
			&AwsElbList{}
			&AwsIamUser{}
			&AwsIamUserList{}
			&AwsKmsAlias{}
			&AwsKmsAliasList{}
			&AwsCloudwatchLogSubscriptionFilter{}
			&AwsCloudwatchLogSubscriptionFilterList{}
			&AwsDynamodbGlobalTable{}
			&AwsDynamodbGlobalTableList{}
			&AwsIamUserLoginProfile{}
			&AwsIamUserLoginProfileList{}
			&AwsNetworkInterfaceAttachment{}
			&AwsNetworkInterfaceAttachmentList{}
			&AwsWafregionalSizeConstraintSet{}
			&AwsWafregionalSizeConstraintSetList{}
			&AwsDmsCertificate{}
			&AwsDmsCertificateList{}
			&AwsEfsMountTarget{}
			&AwsEfsMountTargetList{}
			&AwsEcrRepository{}
			&AwsEcrRepositoryList{}
			&AwsNetworkInterfaceSgAttachment{}
			&AwsNetworkInterfaceSgAttachmentList{}
			&AwsSsmMaintenanceWindowTarget{}
			&AwsSsmMaintenanceWindowTargetList{}
			&AwsVpnConnection{}
			&AwsVpnConnectionList{}
			&AwsWafregionalXssMatchSet{}
			&AwsWafregionalXssMatchSetList{}
			&AwsLbListenerCertificate{}
			&AwsLbListenerCertificateList{}
			&AwsDbSnapshot{}
			&AwsDbSnapshotList{}
			&AwsDbSubnetGroup{}
			&AwsDbSubnetGroupList{}
			&AwsCloudfrontOriginAccessIdentity{}
			&AwsCloudfrontOriginAccessIdentityList{}
			&AwsGlueConnection{}
			&AwsGlueConnectionList{}
			&AwsRouteTable{}
			&AwsRouteTableList{}
			&AwsSnsPlatformApplication{}
			&AwsSnsPlatformApplicationList{}
			&AwsWafregionalIpset{}
			&AwsWafregionalIpsetList{}
			&AwsAmiCopy{}
			&AwsAmiCopyList{}
			&AwsCloudwatchLogDestinationPolicy{}
			&AwsCloudwatchLogDestinationPolicyList{}
			&AwsWafregionalRegexPatternSet{}
			&AwsWafregionalRegexPatternSetList{}
			&AwsLbListener{}
			&AwsLbListenerList{}
			&AwsDynamodbTable{}
			&AwsDynamodbTableList{}
			&AwsSpotInstanceRequest{}
			&AwsSpotInstanceRequestList{}
			&AwsVpcEndpointConnectionNotification{}
			&AwsVpcEndpointConnectionNotificationList{}
			&AwsS3BucketNotification{}
			&AwsS3BucketNotificationList{}
			&AwsSubnet{}
			&AwsSubnetList{}
			&AwsWafGeoMatchSet{}
			&AwsWafGeoMatchSetList{}
			&AwsApiGatewayDeployment{}
			&AwsApiGatewayDeploymentList{}
			&AwsIamAccountPasswordPolicy{}
			&AwsIamAccountPasswordPolicyList{}
			&AwsGlueJob{}
			&AwsGlueJobList{}
			&AwsKmsKey{}
			&AwsKmsKeyList{}
			&AwsLightsailDomain{}
			&AwsLightsailDomainList{}
			&AwsS3BucketMetric{}
			&AwsS3BucketMetricList{}
			&AwsSqsQueuePolicy{}
			&AwsSqsQueuePolicyList{}
			&AwsWafWebAcl{}
			&AwsWafWebAclList{}
			&AwsCloudwatchMetricAlarm{}
			&AwsCloudwatchMetricAlarmList{}
			&AwsCodecommitRepository{}
			&AwsCodecommitRepositoryList{}
			&AwsAlbTargetGroupAttachment{}
			&AwsAlbTargetGroupAttachmentList{}
			&AwsEip{}
			&AwsEipList{}
			&AwsElasticacheCluster{}
			&AwsElasticacheClusterList{}
			&AwsWafXssMatchSet{}
			&AwsWafXssMatchSetList{}
			&AwsAutoscalingPolicy{}
			&AwsAutoscalingPolicyList{}
			&AwsCodedeployApp{}
			&AwsCodedeployAppList{}
			&AwsIamRole{}
			&AwsIamRoleList{}
			&AwsRdsCluster{}
			&AwsRdsClusterList{}
			&AwsDefaultVpc{}
			&AwsDefaultVpcList{}
			&AwsWafregionalRateBasedRule{}
			&AwsWafregionalRateBasedRuleList{}
			&AwsCloudwatchLogDestination{}
			&AwsCloudwatchLogDestinationList{}
			&AwsCloudwatchDashboard{}
			&AwsCloudwatchDashboardList{}
			&AwsEcsCluster{}
			&AwsEcsClusterList{}
			&AwsEmrCluster{}
			&AwsEmrClusterList{}
			&AwsIamRolePolicyAttachment{}
			&AwsIamRolePolicyAttachmentList{}
			&AwsOpsworksPhpAppLayer{}
			&AwsOpsworksPhpAppLayerList{}
			&AwsCloudtrail{}
			&AwsCloudtrailList{}
			&AwsCognitoUserPool{}
			&AwsCognitoUserPoolList{}
			&AwsIamSamlProvider{}
			&AwsIamSamlProviderList{}
			&AwsLightsailStaticIpAttachment{}
			&AwsLightsailStaticIpAttachmentList{}
			&AwsLbSslNegotiationPolicy{}
			&AwsLbSslNegotiationPolicyList{}
			&AwsSesTemplate{}
			&AwsSesTemplateList{}
			&AwsSfnStateMachine{}
			&AwsSfnStateMachineList{}
			&AwsWafIpset{}
			&AwsWafIpsetList{}
			&AwsApiGatewayAccount{}
			&AwsApiGatewayAccountList{}
			&AwsDbInstance{}
			&AwsDbInstanceList{}
			&AwsLbListenerRule{}
			&AwsLbListenerRuleList{}
			&AwsWafregionalRegexMatchSet{}
			&AwsWafregionalRegexMatchSetList{}
			&AwsAlbListenerCertificate{}
			&AwsAlbListenerCertificateList{}
			&AwsIamGroup{}
			&AwsIamGroupList{}
			&AwsSsmDocument{}
			&AwsSsmDocumentList{}
			&AwsSfnActivity{}
			&AwsSfnActivityList{}
			&AwsAcmCertificateValidation{}
			&AwsAcmCertificateValidationList{}
			&AwsElastictranscoderPipeline{}
			&AwsElastictranscoderPipelineList{}
			&AwsOpsworksNodejsAppLayer{}
			&AwsOpsworksNodejsAppLayerList{}
			&AwsProxyProtocolPolicy{}
			&AwsProxyProtocolPolicyList{}
			&AwsConfigConfigRule{}
			&AwsConfigConfigRuleList{}
			&AwsMqConfiguration{}
			&AwsMqConfigurationList{}
			&AwsRdsClusterParameterGroup{}
			&AwsRdsClusterParameterGroupList{}
			&AwsRoute53QueryLog{}
			&AwsRoute53QueryLogList{}
			&AwsSsmPatchGroup{}
			&AwsSsmPatchGroupList{}
			&AwsVpcEndpointRouteTableAssociation{}
			&AwsVpcEndpointRouteTableAssociationList{}
			&AwsEfsFileSystem{}
			&AwsEfsFileSystemList{}
			&AwsElasticBeanstalkApplication{}
			&AwsElasticBeanstalkApplicationList{}
			&AwsNatGateway{}
			&AwsNatGatewayList{}
			&AwsSsmParameter{}
			&AwsSsmParameterList{}
			&AwsLbTargetGroup{}
			&AwsLbTargetGroupList{}
			&AwsElasticBeanstalkApplicationVersion{}
			&AwsElasticBeanstalkApplicationVersionList{}
			&AwsKinesisFirehoseDeliveryStream{}
			&AwsKinesisFirehoseDeliveryStreamList{}
			&AwsDmsEndpoint{}
			&AwsDmsEndpointList{}
			&AwsDynamodbTableItem{}
			&AwsDynamodbTableItemList{}
			&AwsElasticacheSubnetGroup{}
			&AwsElasticacheSubnetGroupList{}
			&AwsIamUserSshKey{}
			&AwsIamUserSshKeyList{}
			&AwsLambdaFunction{}
			&AwsLambdaFunctionList{}
			&AwsOpsworksMysqlLayer{}
			&AwsOpsworksMysqlLayerList{}
			&AwsApiGatewayIntegration{}
			&AwsApiGatewayIntegrationList{}
			&AwsCloud9EnvironmentEc2{}
			&AwsCloud9EnvironmentEc2List{}
			&AwsOrganizationsAccount{}
			&AwsOrganizationsAccountList{}
			&AwsSesReceiptRule{}
			&AwsSesReceiptRuleList{}
			&AwsVpnGateway{}
			&AwsVpnGatewayList{}
			&AwsWafRateBasedRule{}
			&AwsWafRateBasedRuleList{}
			&AwsBatchJobQueue{}
			&AwsBatchJobQueueList{}
			&AwsIamUserPolicy{}
			&AwsIamUserPolicyList{}
			&AwsServiceDiscoveryPublicDnsNamespace{}
			&AwsServiceDiscoveryPublicDnsNamespaceList{}
			&AwsAutoscalingGroup{}
			&AwsAutoscalingGroupList{}
			&AwsCloudwatchEventPermission{}
			&AwsCloudwatchEventPermissionList{}
			&AwsCloudwatchLogStream{}
			&AwsCloudwatchLogStreamList{}
			&AwsConfigConfigurationRecorder{}
			&AwsConfigConfigurationRecorderList{}
			&AwsDaxCluster{}
			&AwsDaxClusterList{}
			&AwsEbsVolume{}
			&AwsEbsVolumeList{}
			&AwsApiGatewayMethodSettings{}
			&AwsApiGatewayMethodSettingsList{}
			&AwsApiGatewayUsagePlanKey{}
			&AwsApiGatewayUsagePlanKeyList{}
			&AwsNetworkInterface{}
			&AwsNetworkInterfaceList{}
			&AwsWafSizeConstraintSet{}
			&AwsWafSizeConstraintSetList{}
			&AwsGameliftBuild{}
			&AwsGameliftBuildList{}
			&AwsIotThing{}
			&AwsIotThingList{}
			&AwsLaunchTemplate{}
			&AwsLaunchTemplateList{}
			&AwsOpsworksInstance{}
			&AwsOpsworksInstanceList{}
			&AwsWafregionalGeoMatchSet{}
			&AwsWafregionalGeoMatchSetList{}
			&AwsApiGatewayDocumentationPart{}
			&AwsApiGatewayDocumentationPartList{}
			&AwsElasticBeanstalkEnvironment{}
			&AwsElasticBeanstalkEnvironmentList{}
			&AwsLambdaEventSourceMapping{}
			&AwsLambdaEventSourceMappingList{}
			&AwsRoute53Zone{}
			&AwsRoute53ZoneList{}
			&AwsDefaultVpcDhcpOptions{}
			&AwsDefaultVpcDhcpOptionsList{}
			&AwsVpnGatewayRoutePropagation{}
			&AwsVpnGatewayRoutePropagationList{}
			&AwsApiGatewayDomainName{}
			&AwsApiGatewayDomainNameList{}
			&AwsMediaStoreContainer{}
			&AwsMediaStoreContainerList{}
			&AwsVpcEndpointServiceAllowedPrincipal{}
			&AwsVpcEndpointServiceAllowedPrincipalList{}
			&AwsLb{}
			&AwsLbList{}
			&AwsOpsworksMemcachedLayer{}
			&AwsOpsworksMemcachedLayerList{}
			&AwsVpcPeeringConnection{}
			&AwsVpcPeeringConnectionList{}
			&AwsIamServerCertificate{}
			&AwsIamServerCertificateList{}
			&AwsVolumeAttachment{}
			&AwsVolumeAttachmentList{}
			&AwsLbTargetGroupAttachment{}
			&AwsLbTargetGroupAttachmentList{}
			&AwsCloudwatchLogMetricFilter{}
			&AwsCloudwatchLogMetricFilterList{}
			&AwsDmsReplicationInstance{}
			&AwsDmsReplicationInstanceList{}
			&AwsEgressOnlyInternetGateway{}
			&AwsEgressOnlyInternetGatewayList{}
			&AwsIamInstanceProfile{}
			&AwsIamInstanceProfileList{}
			&AwsKinesisStream{}
			&AwsKinesisStreamList{}
			&AwsOpsworksApplication{}
			&AwsOpsworksApplicationList{}
			&AwsBatchJobDefinition{}
			&AwsBatchJobDefinitionList{}
			&AwsAmiFromInstance{}
			&AwsAmiFromInstanceList{}
			&AwsEcrRepositoryPolicy{}
			&AwsEcrRepositoryPolicyList{}
			&AwsAutoscalingNotification{}
			&AwsAutoscalingNotificationList{}
			&AwsVpnConnectionRoute{}
			&AwsVpnConnectionRouteList{}
			&AwsCustomerGateway{}
			&AwsCustomerGatewayList{}
			&AwsInspectorAssessmentTarget{}
			&AwsInspectorAssessmentTargetList{}
			&AwsLbCookieStickinessPolicy{}
			&AwsLbCookieStickinessPolicyList{}
			&AwsLoadBalancerBackendServerPolicy{}
			&AwsLoadBalancerBackendServerPolicyList{}
			&AwsOpsworksJavaAppLayer{}
			&AwsOpsworksJavaAppLayerList{}
			&AwsSesReceiptFilter{}
			&AwsSesReceiptFilterList{}
			&AwsCloudwatchLogGroup{}
			&AwsCloudwatchLogGroupList{}
			&AwsCodecommitTrigger{}
			&AwsCodecommitTriggerList{}
			&AwsDbParameterGroup{}
			&AwsDbParameterGroupList{}
			&AwsInternetGateway{}
			&AwsInternetGatewayList{}
			&AwsLambdaAlias{}
			&AwsLambdaAliasList{}
			&AwsOpsworksStack{}
			&AwsOpsworksStackList{}
			&AwsOrganizationsOrganization{}
			&AwsOrganizationsOrganizationList{}
			&AwsBatchComputeEnvironment{}
			&AwsBatchComputeEnvironmentList{}
			&AwsApiGatewayMethod{}
			&AwsApiGatewayMethodList{}
			&AwsAutoscalingSchedule{}
			&AwsAutoscalingScheduleList{}
			&AwsWafregionalRuleGroup{}
			&AwsWafregionalRuleGroupList{}
			&AwsAlbListener{}
			&AwsAlbListenerList{}
			&AwsApiGatewayClientCertificate{}
			&AwsApiGatewayClientCertificateList{}
			&AwsSesConfigurationSet{}
			&AwsSesConfigurationSetList{}
			&AwsOpsworksRailsAppLayer{}
			&AwsOpsworksRailsAppLayerList{}
			&AwsVpcDhcpOptions{}
			&AwsVpcDhcpOptionsList{}
			&AwsDbSecurityGroup{}
			&AwsDbSecurityGroupList{}
			&AwsElasticBeanstalkConfigurationTemplate{}
			&AwsElasticBeanstalkConfigurationTemplateList{}
			&AwsRdsClusterInstance{}
			&AwsRdsClusterInstanceList{}
			&AwsS3BucketObject{}
			&AwsS3BucketObjectList{}
			&AwsSnsTopic{}
			&AwsSnsTopicList{}
			&AwsAppautoscalingPolicy{}
			&AwsAppautoscalingPolicyList{}
			&AwsOpsworksGangliaLayer{}
			&AwsOpsworksGangliaLayerList{}
			&AwsRedshiftSecurityGroup{}
			&AwsRedshiftSecurityGroupList{}
			&AwsRoute53DelegationSet{}
			&AwsRoute53DelegationSetList{}
			&AwsServiceDiscoveryService{}
			&AwsServiceDiscoveryServiceList{}
			&AwsSsmActivation{}
			&AwsSsmActivationList{}
			&AwsConfigConfigurationRecorderStatus{}
			&AwsConfigConfigurationRecorderStatusList{}
			&AwsLaunchConfiguration{}
			&AwsLaunchConfigurationList{}
			&AwsOpsworksPermission{}
			&AwsOpsworksPermissionList{}
			&AwsS3BucketPolicy{}
			&AwsS3BucketPolicyList{}
			&AwsSnapshotCreateVolumePermission{}
			&AwsSnapshotCreateVolumePermissionList{}
			&AwsDirectoryServiceConditionalForwarder{}
			&AwsDirectoryServiceConditionalForwarderList{}
			&AwsOpsworksStaticWebLayer{}
			&AwsOpsworksStaticWebLayerList{}
			&AwsIamPolicyAttachment{}
			&AwsIamPolicyAttachmentList{}
			&AwsMainRouteTableAssociation{}
			&AwsMainRouteTableAssociationList{}
			&AwsSsmMaintenanceWindowTask{}
			&AwsSsmMaintenanceWindowTaskList{}
			&AwsApiGatewayUsagePlan{}
			&AwsApiGatewayUsagePlanList{}
			&AwsElasticsearchDomain{}
			&AwsElasticsearchDomainList{}
			&AwsRoute53HealthCheck{}
			&AwsRoute53HealthCheckList{}
			&AwsSqsQueue{}
			&AwsSqsQueueList{}
			&AwsNetworkAcl{}
			&AwsNetworkAclList{}
			&AwsOpsworksUserProfile{}
			&AwsOpsworksUserProfileList{}
			&AwsApiGatewayVpcLink{}
			&AwsApiGatewayVpcLinkList{}
			&AwsCloudwatchEventRule{}
			&AwsCloudwatchEventRuleList{}
			&AwsEcsTaskDefinition{}
			&AwsEcsTaskDefinitionList{}
			&AwsElasticsearchDomainPolicy{}
			&AwsElasticsearchDomainPolicyList{}
			&AwsElastictranscoderPreset{}
			&AwsElastictranscoderPresetList{}
			&AwsRedshiftSubnetGroup{}
			&AwsRedshiftSubnetGroupList{}
			&AwsApiGatewayAuthorizer{}
			&AwsApiGatewayAuthorizerList{}
			&AwsApiGatewayBasePathMapping{}
			&AwsApiGatewayBasePathMappingList{}
			&AwsVpcEndpoint{}
			&AwsVpcEndpointList{}
			&AwsSecurityGroupRule{}
			&AwsSecurityGroupRuleList{}
			&AwsSpotDatafeedSubscription{}
			&AwsSpotDatafeedSubscriptionList{}
			&AwsSsmAssociation{}
			&AwsSsmAssociationList{}
			&AwsSnsTopicPolicy{}
			&AwsSnsTopicPolicyList{}
			&AwsAutoscalingAttachment{}
			&AwsAutoscalingAttachmentList{}
			&AwsGameliftAlias{}
			&AwsGameliftAliasList{}
			&AwsDxConnectionAssociation{}
			&AwsDxConnectionAssociationList{}
			&AwsEipAssociation{}
			&AwsEipAssociationList{}
			&AwsGlacierVault{}
			&AwsGlacierVaultList{}
			&AwsKmsGrant{}
			&AwsKmsGrantList{}
			&AwsSesIdentityNotificationTopic{}
			&AwsSesIdentityNotificationTopicList{}
			&AwsApiGatewayModel{}
			&AwsApiGatewayModelList{}
			&AwsCloudwatchEventTarget{}
			&AwsCloudwatchEventTargetList{}
			&AwsWafSqlInjectionMatchSet{}
			&AwsWafSqlInjectionMatchSetList{}
			&AwsElasticacheSecurityGroup{}
			&AwsElasticacheSecurityGroupList{}
			&AwsVpcEndpointService{}
			&AwsVpcEndpointServiceList{}
			&AwsRoute53ZoneAssociation{}
			&AwsRoute53ZoneAssociationList{}
			&AwsSecurityGroup{}
			&AwsSecurityGroupList{}
			&AwsSsmMaintenanceWindow{}
			&AwsSsmMaintenanceWindowList{}
			&AwsApiGatewayMethodResponse{}
			&AwsApiGatewayMethodResponseList{}
			&AwsOpsworksHaproxyLayer{}
			&AwsOpsworksHaproxyLayerList{}
			&AwsIamRolePolicy{}
			&AwsIamRolePolicyList{}
			&AwsIotCertificate{}
			&AwsIotCertificateList{}
			&AwsSesActiveReceiptRuleSet{}
			&AwsSesActiveReceiptRuleSetList{}
			&AwsWafRule{}
			&AwsWafRuleList{}
			&AwsAutoscalingLifecycleHook{}
			&AwsAutoscalingLifecycleHookList{}
			&AwsCognitoIdentityPoolRolesAttachment{}
			&AwsCognitoIdentityPoolRolesAttachmentList{}
			&AwsEcrLifecyclePolicy{}
			&AwsEcrLifecyclePolicyList{}
			&AwsGlueCatalogDatabase{}
			&AwsGlueCatalogDatabaseList{}
			&AwsLambdaPermission{}
			&AwsLambdaPermissionList{}
			&AwsLightsailInstance{}
			&AwsLightsailInstanceList{}
			&AwsLoadBalancerPolicy{}
			&AwsLoadBalancerPolicyList{}
			&AwsMqBroker{}
			&AwsMqBrokerList{}
			&AwsApiGatewayStage{}
			&AwsApiGatewayStageList{}
			&AwsConfigDeliveryChannel{}
			&AwsConfigDeliveryChannelList{}
			&AwsSesDomainIdentityVerification{}
			&AwsSesDomainIdentityVerificationList{}
			&AwsOpsworksRdsDbInstance{}
			&AwsOpsworksRdsDbInstanceList{}
			&AwsPlacementGroup{}
			&AwsPlacementGroupList{}
			&AwsIamAccessKey{}
			&AwsIamAccessKeyList{}
			&AwsDevicefarmProject{}
			&AwsDevicefarmProjectList{}
			&AwsGuarddutyIpset{}
			&AwsGuarddutyIpsetList{}
			&AwsIamOpenidConnectProvider{}
			&AwsIamOpenidConnectProviderList{}
			&AwsIamServiceLinkedRole{}
			&AwsIamServiceLinkedRoleList{}
			&AwsInspectorResourceGroup{}
			&AwsInspectorResourceGroupList{}
			&AwsLightsailStaticIp{}
			&AwsLightsailStaticIpList{}
			&AwsServicecatalogPortfolio{}
			&AwsServicecatalogPortfolioList{}
			&AwsApiGatewayApiKey{}
			&AwsApiGatewayApiKeyList{}
			&AwsCloudfrontDistribution{}
			&AwsCloudfrontDistributionList{}
			&AwsRoute{}
			&AwsRouteList{}
			&AwsDefaultRouteTable{}
			&AwsDefaultRouteTableList{}
			&AwsVpcDhcpOptionsAssociation{}
			&AwsVpcDhcpOptionsAssociationList{}
			&AwsGameliftFleet{}
			&AwsGameliftFleetList{}
			&AwsIamGroupPolicyAttachment{}
			&AwsIamGroupPolicyAttachmentList{}
			&AwsIamUserPolicyAttachment{}
			&AwsIamUserPolicyAttachmentList{}
			&AwsDefaultNetworkAcl{}
			&AwsDefaultNetworkAclList{}
			&AwsSesDomainDkim{}
			&AwsSesDomainDkimList{}
			&AwsAppautoscalingScheduledAction{}
			&AwsAppautoscalingScheduledActionList{}
			&AwsDxLag{}
			&AwsDxLagList{}
			&AwsWafregionalRule{}
			&AwsWafregionalRuleList{}
			&AwsAlb{}
			&AwsAlbList{}
			&AwsApiGatewayResource{}
			&AwsApiGatewayResourceList{}
			&AwsDbEventSubscription{}
			&AwsDbEventSubscriptionList{}
			&AwsDirectoryServiceDirectory{}
			&AwsDirectoryServiceDirectoryList{}
			&AwsSesDomainMailFrom{}
			&AwsSesDomainMailFromList{}
			&AwsApiGatewayRestApi{}
			&AwsApiGatewayRestApiList{}
			&AwsCloudwatchLogResourcePolicy{}
			&AwsCloudwatchLogResourcePolicyList{}
			&AwsIamGroupPolicy{}
			&AwsIamGroupPolicyList{}
			&AwsSsmPatchBaseline{}
			&AwsSsmPatchBaselineList{}
			&AwsSnsTopicSubscription{}
			&AwsSnsTopicSubscriptionList{}
			&AwsCognitoUserPoolClient{}
			&AwsCognitoUserPoolClientList{}
			&AwsIamAccountAlias{}
			&AwsIamAccountAliasList{}
			&AwsCodebuildProject{}
			&AwsCodebuildProjectList{}
			&AwsIamGroupMembership{}
			&AwsIamGroupMembershipList{}
			&AwsSesReceiptRuleSet{}
			&AwsSesReceiptRuleSetList{}
			&AwsVpcEndpointSubnetAssociation{}
			&AwsVpcEndpointSubnetAssociationList{}
			&AwsAthenaDatabase{}
			&AwsAthenaDatabaseList{}
			&AwsCodedeployDeploymentConfig{}
			&AwsCodedeployDeploymentConfigList{}
)
	
		// register the type in the scheme
		meta_v1.AddToGroupVersion(scheme, SchemeGroupVersion)
		return nil
	}